import assert from 'node:assert/strict'
import { execFile } from 'node:child_process'
import { generateKeyPairSync } from 'node:crypto'
import { chmod, mkdir, mkdtemp, readFile, realpath, rm, unlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import test, { type TestContext } from 'node:test'
import { promisify } from 'node:util'
import { provisionInactiveServerConfiguration } from '../src/control-plane/server-configuration.js'
import { sealServerDistribution } from '../src/control-plane/server-distribution.js'
import { installInactiveServer } from '../src/control-plane/server-installation.js'
import { bootstrapInstalledFirstOwner, recoverInstalledFirstOwner, repairInstalledFirstOwnerReceipt } from '../src/control-plane/server-owner-bootstrap.js'
import { openSqliteCloudIdentityProvider } from '../src/control-plane/sqlite-cloud-identity.js'

const run = promisify(execFile); const migrationNames = ['001_tenant_identity.sql','002_agent_studio.sql','003_capability_registry.sql','004_device_sessions.sql','005_device_enrollment.sql','006_cloud_identity.sql','007_identity_administration.sql']; const sourceMigrations = new URL('../migrations/control-plane-sqlite/', import.meta.url).pathname

test('creates and recovers one installed owner while every runtime activation remains off', async t => { const fixture = await setup(t); if (!fixture) return; const { parent, install } = fixture; const now = new Date('2026-09-06T00:00:00.000Z'); try { const receipt = await bootstrapInstalledFirstOwner({ installRoot: install, tenantId: 'tenant.alpha', tenantName: 'Alpha', userId: 'owner', displayName: 'Owner' }, 'synthetic-password', now); assert.equal(receipt.state, 'owner-created-inactive'); assert.equal(receipt.serviceRegistered, false); assert.equal(receipt.externalEffectsEnabled, false); assert.deepEqual(await recoverInstalledFirstOwner(install), receipt); const identity = await openSqliteCloudIdentityProvider(join(install, 'state/control.sqlite3'), [join(install, 'program/migrations/control-plane-sqlite/001_tenant_identity.sql'), join(install, 'program/migrations/control-plane-sqlite/006_cloud_identity.sql')], { tenantAdmission: 'registered' }); const session = await identity.authenticate({ tenantId: 'tenant.alpha', userId: 'owner', password: 'synthetic-password' }, now); assert.deepEqual(await identity.resolveSession(session.sessionReference, now), { tenantId: 'tenant.alpha', userId: 'owner', roles: ['owner'] }); await identity.close(); assert.equal((await readFile(join(install, 'state/control.sqlite3'))).includes(Buffer.from('synthetic-password')), false); await assert.rejects(bootstrapInstalledFirstOwner({ installRoot: install, tenantId: 'tenant.beta', tenantName: 'Beta', userId: 'owner', displayName: 'Owner' }, 'another-password'), /unused runtime and state/) } finally { await rm(parent, { recursive: true, force: true }) } })

test('fails recovery when the receipt no longer identifies the singleton database owner', async t => { const fixture = await setup(t); if (!fixture) return; const { parent, install } = fixture; try { await bootstrapInstalledFirstOwner({ installRoot: install, tenantId: 'tenant.alpha', tenantName: 'Alpha', userId: 'owner', displayName: 'Owner' }, 'synthetic-password'); const path = join(install, 'state/owner-bootstrap-receipt.json'); const receipt = JSON.parse(await readFile(path, 'utf8')); receipt.userId = 'another'; await writeFile(path, `${JSON.stringify(receipt)}\n`, { mode: 0o600 }); await assert.rejects(recoverInstalledFirstOwner(install), /database is invalid/) } finally { await rm(parent, { recursive: true, force: true }) } })
test('repairs only a missing receipt whose expected singleton identity matches', async t => { const fixture = await setup(t); if (!fixture) return; const { parent, install } = fixture; try { const original = await bootstrapInstalledFirstOwner({ installRoot: install, tenantId: 'tenant.alpha', tenantName: 'Alpha', userId: 'owner', displayName: 'Owner' }, 'synthetic-password', new Date('2026-09-06T00:00:00.000Z')); const path = join(install, 'state/owner-bootstrap-receipt.json'); await unlink(path); await assert.rejects(repairInstalledFirstOwnerReceipt({ installRoot: install, tenantId: 'tenant.beta', userId: 'owner' }), /identity is invalid/); await assert.rejects(readFile(path), /ENOENT/); assert.deepEqual(await repairInstalledFirstOwnerReceipt({ installRoot: install, tenantId: 'tenant.alpha', userId: 'owner' }), original); assert.deepEqual(await recoverInstalledFirstOwner(install), original) } finally { await rm(parent, { recursive: true, force: true }) } })

async function setup(t: TestContext): Promise<{ parent: string; install: string } | undefined> { const created = await mkdtemp(join(tmpdir(), 'quark-installed-owner-')); await chmod(created, 0o700); const parent = await realpath(created); const source = join(parent, 'distribution'); const install = join(parent, 'installed'); const keyPath = join(parent, 'source-key.pem'); const certPath = join(parent, 'source-cert.pem'); try { try { await run('/usr/bin/openssl', ['req','-x509','-newkey','rsa:2048','-nodes','-keyout',keyPath,'-out',certPath,'-subj','/CN=127.0.0.1','-days','1'], { timeout: 10_000 }) } catch { t.skip('host openssl is unavailable'); await rm(parent, { recursive: true, force: true }); return }; await chmod(keyPath, 0o600); await chmod(certPath, 0o600); await distribution(source); await installInactiveServer(install, source); const publicKey = `ed25519-spki:${(generateKeyPairSync('ed25519').publicKey.export({ format: 'der', type: 'spki' }) as Buffer).toString('base64url')}`; await provisionInactiveServerConfiguration({ installRoot: install, tlsKeySourcePath: keyPath, tlsCertSourcePath: certPath, host: '127.0.0.1', port: 8443, requestTimeoutMs: 5_000, maxConnections: 100, sshRequestTimeoutMs: 5_000, planVerification: { keyId: 'control.primary', publicKey } }); return { parent, install } } catch (error) { await rm(parent, { recursive: true, force: true }); throw error } }
async function distribution(root: string): Promise<void> { await mkdir(root, { mode: 0o700 }); const files = ['dist/control-plane/cloud-server-entry.js','dist/control-plane/server-admin-entry.js','dist/client-runtime/ssh-subsystem-entry.js','package.json','sbom.spdx.json']; for (const path of files) { const target = join(root, 'program', path); await mkdir(dirname(target), { recursive: true, mode: 0o700 }); await writeFile(target, `fixture:${path}\n`, { mode: 0o600 }) }; for (const name of migrationNames) { const target = join(root, 'program/migrations/control-plane-sqlite', name); await mkdir(dirname(target), { recursive: true, mode: 0o700 }); await writeFile(target, await readFile(join(sourceMigrations, name)), { mode: 0o600 }) }; await sealServerDistribution(await realpath(root), '0.1.0', 'a'.repeat(40)) }
