import assert from 'node:assert/strict'
import { chmod, mkdir, mkdtemp, realpath, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import test from 'node:test'
import { sealServerDistribution } from '../src/control-plane/server-distribution.js'
import { installInactiveServer, recoverInactiveServerInstallation, uninstallUnusedInactiveServer } from '../src/control-plane/server-installation.js'

const files = ['dist/control-plane/cloud-server-entry.js','dist/control-plane/server-admin-entry.js','dist/client-runtime/ssh-subsystem-entry.js','package.json','sbom.spdx.json', ...['001_tenant_identity.sql','002_agent_studio.sql','003_capability_registry.sql','004_device_sessions.sql','005_device_enrollment.sql','006_cloud_identity.sql','007_identity_administration.sql'].map(name => `migrations/control-plane-sqlite/${name}`)]
test('installs, recovers and uninstalls an unused inactive server without checkout paths', async () => { const parent = await privateTemp(); const source = join(parent, 'source'); const install = join(parent, 'server'); try { await distribution(source); await assert.rejects(installInactiveServer(join(parent, 'x'.repeat(101)), source), /cannot host a portable Unix socket/); const receipt = await installInactiveServer(install, source, new Date('2026-09-06T00:00:00.000Z')); assert.equal(receipt.state, 'installed-inactive'); assert.equal(receipt.autoStart, false); assert.equal(receipt.serviceRegistered, false); assert.deepEqual(await recoverInactiveServerInstallation(install), receipt); assert.deepEqual(await uninstallUnusedInactiveServer(install), receipt); await assert.rejects(realpath(install), /ENOENT/) } finally { await rm(parent, { recursive: true, force: true }) } })
test('detects distribution drift and never removes durable server state', async () => { const parent = await privateTemp(); const source = join(parent, 'source'); const install = join(parent, 'server'); try { await distribution(source); await installInactiveServer(install, source); await writeFile(join(install, 'state', 'tenant.sqlite3'), 'durable', { mode: 0o600 }); await assert.rejects(uninstallUnusedInactiveServer(install), /durable state/); assert.equal(await realpath(install), install); await writeFile(join(install, 'program/package.json'), 'tampered', { mode: 0o600 }); await assert.rejects(recoverInactiveServerInstallation(install), /inventory drifted/) } finally { await rm(parent, { recursive: true, force: true }) } })
async function privateTemp(): Promise<string> { const created = await mkdtemp(join(await realpath('/tmp'), 'qsi-')); await chmod(created, 0o700); return await realpath(created) }
async function distribution(root: string): Promise<void> { await mkdir(root, { mode: 0o700 }); for (const path of files) { const target = join(root, 'program', path); await mkdir(dirname(target), { recursive: true, mode: 0o700 }); await writeFile(target, `fixture:${path}\n`, { mode: 0o600 }) }; await sealServerDistribution(await realpath(root), '0.1.0', 'a'.repeat(40)) }
