import assert from 'node:assert/strict'
import { execFile } from 'node:child_process'
import { createHash, generateKeyPairSync } from 'node:crypto'
import { chmod, mkdir, mkdtemp, readFile, realpath, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { promisify } from 'node:util'
import test, { type TestContext } from 'node:test'
import { provisionInactiveServerConfiguration, recoverInactiveServerConfiguration, removeUnusedServerConfiguration } from '../src/control-plane/server-configuration.js'
import { sealServerDistribution } from '../src/control-plane/server-distribution.js'
import { installInactiveServer } from '../src/control-plane/server-installation.js'

const run = promisify(execFile)
const files = ['dist/control-plane/cloud-server-entry.js','dist/client-runtime/ssh-subsystem-entry.js','package.json','sbom.spdx.json', ...['001_tenant_identity.sql','002_agent_studio.sql','003_capability_registry.sql','004_device_sessions.sql','005_device_enrollment.sql','006_cloud_identity.sql','007_identity_administration.sql'].map(name => `migrations/control-plane-sqlite/${name}`)]

test('provisions, recovers and removes unchanged inactive host configuration', async t => { const fixture = await setup(t); if (!fixture) return; const { parent, install, input } = fixture; try { const receipt = await provisionInactiveServerConfiguration(input, new Date('2026-09-06T00:00:00.000Z')); assert.equal(receipt.state, 'configured-inactive'); assert.equal(receipt.databaseInitialized, false); assert.equal(receipt.serviceRegistered, false); assert.deepEqual(await recoverInactiveServerConfiguration(install), receipt); const config = JSON.parse(await readFile(join(install, 'config/server.json'), 'utf8')); assert.equal(config.runtime.host.composition.databasePath, join(install, 'state/control.sqlite3')); assert.equal(config.runtime.host.composition.migrations.identity, join(install, 'program/migrations/control-plane-sqlite/006_cloud_identity.sql')); assert.deepEqual(await removeUnusedServerConfiguration(install), receipt); assert.deepEqual(await readFile(join(install, 'install-receipt.json'), 'utf8').then(() => true), true) } finally { await rm(parent, { recursive: true, force: true }) } })
test('detects credential drift and refuses rollback after durable state appears', async t => { const fixture = await setup(t); if (!fixture) return; const { parent, install, input } = fixture; try { await provisionInactiveServerConfiguration(input); const cert = await readFile(join(install, 'config/tls-cert.pem')); await writeFile(join(install, 'config/tls-cert.pem'), Buffer.concat([cert, Buffer.from('\n')]), { mode: 0o600 }); await assert.rejects(recoverInactiveServerConfiguration(install), /digest drifted/); await writeFile(join(install, 'config/tls-cert.pem'), cert, { mode: 0o600 }); await writeFile(join(install, 'state/control.sqlite3'), 'durable', { mode: 0o600 }); await assert.rejects(removeUnusedServerConfiguration(install), /runtime or durable state/) } finally { await rm(parent, { recursive: true, force: true }) } })
test('rejects an activation-shaped config even when its receipt digest is rewritten', async t => { const fixture = await setup(t); if (!fixture) return; const { parent, install, input } = fixture; try { await provisionInactiveServerConfiguration(input); const configPath = join(install, 'config/server.json'); const receiptPath = join(install, 'config/configuration-receipt.json'); const config = JSON.parse(await readFile(configPath, 'utf8')); config.runtime.host.activationAllowed = true; const bytes = Buffer.from(`${JSON.stringify(config)}\n`); await writeFile(configPath, bytes, { mode: 0o600 }); const receipt = JSON.parse(await readFile(receiptPath, 'utf8')); receipt.configDigest = `sha256:${createHash('sha256').update(bytes).digest('hex')}`; await writeFile(receiptPath, `${JSON.stringify(receipt)}\n`, { mode: 0o600 }); await assert.rejects(recoverInactiveServerConfiguration(install), /content is invalid/) } finally { await rm(parent, { recursive: true, force: true }) } })

async function setup(t: TestContext): Promise<{ parent: string; install: string; input: Parameters<typeof provisionInactiveServerConfiguration>[0] } | undefined> { const created = await mkdtemp(join(tmpdir(), 'quark-server-config-')); await chmod(created, 0o700); const parent = await realpath(created); const source = join(parent, 'distribution'); const install = join(parent, 'installed'); const keyPath = join(parent, 'source-key.pem'); const certPath = join(parent, 'source-cert.pem'); try { try { await run('/usr/bin/openssl', ['req','-x509','-newkey','rsa:2048','-nodes','-keyout',keyPath,'-out',certPath,'-subj','/CN=127.0.0.1','-days','1'], { timeout: 10_000 }) } catch { t.skip('host openssl is unavailable'); await rm(parent, { recursive: true, force: true }); return }; await chmod(keyPath, 0o600); await chmod(certPath, 0o600); await distribution(source); await installInactiveServer(install, source); const publicKey = `ed25519-spki:${(generateKeyPairSync('ed25519').publicKey.export({ format: 'der', type: 'spki' }) as Buffer).toString('base64url')}`; return { parent, install, input: { installRoot: install, tlsKeySourcePath: keyPath, tlsCertSourcePath: certPath, host: '127.0.0.1', port: 8443, requestTimeoutMs: 5_000, maxConnections: 100, sshRequestTimeoutMs: 5_000, planVerification: { keyId: 'control.primary', publicKey } } } } catch (error) { await rm(parent, { recursive: true, force: true }); throw error } }
async function distribution(root: string): Promise<void> { await mkdir(root, { mode: 0o700 }); for (const path of files) { const target = join(root, 'program', path); await mkdir(dirname(target), { recursive: true, mode: 0o700 }); await writeFile(target, `fixture:${path}\n`, { mode: 0o600 }) }; await sealServerDistribution(await realpath(root), '0.1.0', 'a'.repeat(40)) }
