import assert from 'node:assert/strict'
import { chmod, mkdir, mkdtemp, realpath, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import test from 'node:test'
import { sealServerDistribution, verifyServerDistribution } from '../src/control-plane/server-distribution.js'

const required = ['dist/control-plane/cloud-server-entry.js','dist/control-plane/server-admin-entry.js','dist/client-runtime/ssh-subsystem-entry.js','package.json','sbom.spdx.json', ...['001_tenant_identity.sql','002_agent_studio.sql','003_capability_registry.sql','004_device_sessions.sql','005_device_enrollment.sql','006_cloud_identity.sql','007_identity_administration.sql'].map(name => `migrations/control-plane-sqlite/${name}`)]
test('seals and verifies a host-neutral inactive server distribution', async () => { const root = await fixture(); try { const manifest = await sealServerDistribution(root, '0.1.0', 'a'.repeat(40)); assert.equal(manifest.files.length, required.length); assert.equal(manifest.autoStart, false); assert.equal(manifest.sshGatewayApplied, false); assert.equal(manifest.externalEffectsEnabled, false); assert.deepEqual(await verifyServerDistribution(root), manifest); await writeFile(join(root, 'program/package.json'), 'tampered', { mode: 0o600 }); await assert.rejects(verifyServerDistribution(root), /inventory drifted/) } finally { await rm(root, { recursive: true, force: true }) } })
test('rejects incomplete, public and already sealed distributions', async () => { const root = await fixture(); try { await rm(join(root, 'program/sbom.spdx.json')); await assert.rejects(sealServerDistribution(root, '0.1.0', 'a'.repeat(40)), /incomplete/); await writeFile(join(root, 'program/sbom.spdx.json'), 'sbom', { mode: 0o600 }); await chmod(join(root, 'program/package.json'), 0o644); await assert.rejects(sealServerDistribution(root, '0.1.0', 'a'.repeat(40)), /unsafe/); await chmod(join(root, 'program/package.json'), 0o600); await sealServerDistribution(root, '0.1.0', 'a'.repeat(40)); await assert.rejects(sealServerDistribution(root, '0.1.0', 'a'.repeat(40)), /already sealed/) } finally { await rm(root, { recursive: true, force: true }) } })
async function fixture(): Promise<string> { const created = await mkdtemp(join(tmpdir(), 'quark-server-distribution-')); await chmod(created, 0o700); const root = await realpath(created); for (const path of required) { const destination = join(root, 'program', path); await mkdir(join(destination, '..'), { recursive: true, mode: 0o700 }); await writeFile(destination, `fixture:${path}\n`, { mode: 0o600 }) }; return root }
