import assert from 'node:assert/strict'
import { execFile } from 'node:child_process'
import { generateKeyPairSync } from 'node:crypto'
import { chmod, mkdir, mkdtemp, readFile, readdir, realpath, rm, unlink, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { promisify } from 'node:util'
import test, { type TestContext } from 'node:test'
import { provisionInactiveServerConfiguration } from '../src/control-plane/server-configuration.js'
import { sealServerDistribution } from '../src/control-plane/server-distribution.js'
import { installInactiveServer } from '../src/control-plane/server-installation.js'
import { bootstrapInstalledFirstOwner } from '../src/control-plane/server-owner-bootstrap.js'
import { prepareInstalledServerUserService, recoverPreparedServerUserService, removeUnregisteredServerUserService } from '../src/control-plane/server-service.js'

const run = promisify(execFile); const migrations = ['001_tenant_identity.sql','002_agent_studio.sql','003_capability_registry.sql','004_device_sessions.sql','005_device_enrollment.sql','006_cloud_identity.sql','007_identity_administration.sql']; const sourceMigrations = new URL('../migrations/control-plane-sqlite/', import.meta.url).pathname

test('persists and recovers a sealed inactive LaunchAgent definition without registering it', async t => { const fixture = await setup(t); if (!fixture) return; const { parent, install } = fixture; try { const input = { installRoot: install, platform: 'launchd-user' as const, nodeExecutable: process.execPath, stdoutPath: join(parent, 'server.out'), stderrPath: join(parent, 'server.err') }; const receipt = await prepareInstalledServerUserService(input, new Date('2026-09-06T00:00:00.000Z')); assert.equal(receipt.state, 'service-prepared-inactive'); assert.equal(receipt.registered, false); assert.equal(receipt.started, false); assert.equal(receipt.autoStart, false); assert.deepEqual(await recoverPreparedServerUserService(install), receipt); const definition = await readFile(join(install, 'service/com.quarkfan.quark-server.plist'), 'utf8'); assert.match(definition, /QUARK_CLOUD_SERVER_ENABLE/); assert.doesNotMatch(definition, /API_KEY|TOKEN|PASSWORD|PRIVATE_KEY/); await assert.rejects(prepareInstalledServerUserService(input), /already exists/) } finally { await rm(parent, { recursive: true, force: true }) } })

test('removes only an unchanged unregistered systemd preparation with no runtime owner', async t => { const fixture = await setup(t); if (!fixture) return; const { parent, install } = fixture; try { const input = { installRoot: install, platform: 'systemd-user' as const, nodeExecutable: process.execPath, stdoutPath: join(parent, 'server.out'), stderrPath: join(parent, 'server.err') }; const receipt = await prepareInstalledServerUserService(input); await writeFile(join(install, 'runtime/unknown'), 'retain\n', { mode: 0o600 }); await assert.rejects(removeUnregisteredServerUserService(install), /runtime state/); await unlink(join(install, 'runtime/unknown')); assert.deepEqual(await removeUnregisteredServerUserService(install), receipt); assert.deepEqual(await readdir(join(install, 'service')), []) } finally { await rm(parent, { recursive: true, force: true }) } })

test('detects prepared service definition and receipt drift without deleting evidence', async t => { const fixture = await setup(t); if (!fixture) return; const { parent, install } = fixture; try { await prepareInstalledServerUserService({ installRoot: install, platform: 'launchd-user', nodeExecutable: process.execPath, stdoutPath: join(parent, 'server.out'), stderrPath: join(parent, 'server.err') }); const definition = join(install, 'service/com.quarkfan.quark-server.plist'); await writeFile(definition, 'tampered\n', { mode: 0o600 }); await assert.rejects(recoverPreparedServerUserService(install), /digest drifted/); assert.equal(await readFile(definition, 'utf8'), 'tampered\n') } finally { await rm(parent, { recursive: true, force: true }) } })

async function setup(t: TestContext): Promise<{ parent: string; install: string } | undefined> { const parent = await realpath(await mkdtemp(join(await realpath('/tmp'), 'qsp-'))); await chmod(parent, 0o700); const distribution = join(parent, 'distribution'); const install = join(parent, 'installed'); const key = join(parent, 'key.pem'); const cert = join(parent, 'cert.pem'); try { try { await run('/usr/bin/openssl', ['req','-x509','-newkey','rsa:2048','-nodes','-keyout',key,'-out',cert,'-subj','/CN=127.0.0.1','-days','1'], { timeout: 10_000 }) } catch { t.skip('host openssl is unavailable'); await rm(parent, { recursive: true, force: true }); return }; await chmod(key, 0o600); await chmod(cert, 0o600); await distributionFixture(distribution); await installInactiveServer(install, distribution); const publicKey = `ed25519-spki:${(generateKeyPairSync('ed25519').publicKey.export({ format: 'der', type: 'spki' }) as Buffer).toString('base64url')}`; await provisionInactiveServerConfiguration({ installRoot: install, tlsKeySourcePath: key, tlsCertSourcePath: cert, host: '127.0.0.1', port: 8443, requestTimeoutMs: 5_000, maxConnections: 100, sshRequestTimeoutMs: 5_000, planVerification: { keyId: 'control.primary', publicKey } }); await bootstrapInstalledFirstOwner({ installRoot: install, tenantId: 'tenant.alpha', tenantName: 'Alpha', userId: 'owner', displayName: 'Owner' }, 'synthetic-password'); return { parent, install } } catch (error) { await rm(parent, { recursive: true, force: true }); throw error } }
async function distributionFixture(root: string): Promise<void> { await mkdir(root, { mode: 0o700 }); const ordinary = ['dist/control-plane/cloud-server-entry.js','dist/control-plane/server-admin-entry.js','dist/client-runtime/ssh-subsystem-entry.js','package.json','sbom.spdx.json']; for (const path of ordinary) { const target = join(root, 'program', path); await mkdir(dirname(target), { recursive: true, mode: 0o700 }); await writeFile(target, `fixture:${path}\n`, { mode: 0o600 }) }; for (const path of ['deploy/launchd/com.quarkfan.quark-server.plist.template','deploy/systemd/quark-server.service.template']) { const target = join(root, 'program', path); await mkdir(dirname(target), { recursive: true, mode: 0o700 }); await writeFile(target, await readFile(new URL(`../${path}`, import.meta.url)), { mode: 0o600 }) }; for (const name of migrations) { const target = join(root, 'program/migrations/control-plane-sqlite', name); await mkdir(dirname(target), { recursive: true, mode: 0o700 }); await writeFile(target, await readFile(join(sourceMigrations, name)), { mode: 0o600 }) }; await sealServerDistribution(await realpath(root), '0.1.0', 'a'.repeat(40)) }
