import { createHash } from 'node:crypto'
import { isAbsolute, join, resolve } from 'node:path'

export interface ServerServiceRenderOptionsV1 { readonly installRoot: string; readonly nodeExecutable: string; readonly stdoutPath: string; readonly stderrPath: string }
export interface PreparedServerServiceV1 { readonly schemaVersion: 1; readonly platform: 'launchd-user' | 'systemd-user'; readonly definition: string; readonly definitionDigest: string; readonly state: 'prepared-inactive'; readonly registered: false; readonly started: false; readonly singleProvider: true; readonly externalEffectsEnabled: false; readonly rollback: { readonly stopBeforeRemove: true; readonly removeDefinitionOnly: true; readonly preserveInstallationState: true } }

/** Renders one user LaunchAgent only. It does not write, register or start it. */
export function prepareInactiveServerLaunchd(template: string, options: ServerServiceRenderOptionsV1): PreparedServerServiceV1 { const values = checked(options); return prepared('launchd-user', replace(template, { __NODE_EXECUTABLE__: xml(values.nodeExecutable), __SERVER_ENTRY__: xml(join(values.installRoot, 'program/dist/control-plane/cloud-server-entry.js')), __SERVER_CONFIG__: xml(join(values.installRoot, 'config/server.json')), __PROGRAM_ROOT__: xml(join(values.installRoot, 'program')), __STDOUT_PATH__: xml(values.stdoutPath), __STDERR_PATH__: xml(values.stderrPath) })) }

/** Renders one systemd user unit only. It does not write, enable or start it. */
export function prepareInactiveServerSystemd(template: string, options: ServerServiceRenderOptionsV1): PreparedServerServiceV1 { const values = checked(options); for (const value of Object.values(values)) if (/\s|["\\]/.test(value)) throw new Error('systemd server service paths cannot contain whitespace, quote or backslash'); return prepared('systemd-user', replace(template, { __NODE_EXECUTABLE__: values.nodeExecutable, __SERVER_ENTRY__: join(values.installRoot, 'program/dist/control-plane/cloud-server-entry.js'), __SERVER_CONFIG__: join(values.installRoot, 'config/server.json'), __PROGRAM_ROOT__: join(values.installRoot, 'program'), __STDOUT_PATH__: values.stdoutPath, __STDERR_PATH__: values.stderrPath })) }

function checked(options: ServerServiceRenderOptionsV1): ServerServiceRenderOptionsV1 { if (!options || typeof options !== 'object' || Object.keys(options).sort().join(',') !== ['installRoot','nodeExecutable','stdoutPath','stderrPath'].sort().join(',')) throw new Error('server service options are invalid'); for (const value of Object.values(options)) if (!isAbsolute(value) || resolve(value) !== value || value === '/' || /[\0\r\n]/.test(value)) throw new Error('server service paths must be exact and absolute'); return options }
function replace(template: string, values: Readonly<Record<string, string>>): string { let output = template; for (const [key, value] of Object.entries(values)) output = output.replaceAll(key, value); if (/__[A-Z_]+__/.test(output)) throw new Error('server service template contains unresolved placeholders'); return output }
function prepared(platform: PreparedServerServiceV1['platform'], definition: string): PreparedServerServiceV1 { if (!definition.includes('QUARK_CLOUD_SERVER_ENABLE') || /API_KEY|TOKEN|PASSWORD|PRIVATE_KEY|CLIENT_SECRET/i.test(definition)) throw new Error('server service definition is unsafe'); return Object.freeze({ schemaVersion: 1, platform, definition, definitionDigest: `sha256:${createHash('sha256').update(definition).digest('hex')}`, state: 'prepared-inactive', registered: false, started: false, singleProvider: true, externalEffectsEnabled: false, rollback: Object.freeze({ stopBeforeRemove: true, removeDefinitionOnly: true, preserveInstallationState: true }) }) }
function xml(value: string): string { return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&apos;') }
