import { chmod, lstat, mkdir, open, readFile, realpath, rename, rm, unlink } from 'node:fs/promises'
import { isAbsolute, join, resolve } from 'node:path'
import { copyServerDistribution, recoverInactiveServerInstallation, type InactiveServerInstallationReceipt, type InactiveServerInstallationReceiptV2 } from './server-installation.js'
import { verifyServerDistribution, type ServerDistributionManifestV1 } from './server-distribution.js'
import { recoverPreparedServerUserService } from './server-service.js'

export interface InactiveServerProgramUpgradeReceiptV1 { readonly schemaVersion: 1; readonly installationId: string; readonly fromVersion: string; readonly fromRevision: string; readonly toVersion: string; readonly toRevision: string; readonly upgradedAt: string; readonly state: 'upgraded-inactive'; readonly rollbackPrepared: true; readonly serviceRegistered: false; readonly externalEffectsEnabled: false }
interface UpgradeIntentV1 { readonly schemaVersion: 1; readonly installationId: string; readonly priorReceipt: InactiveServerInstallationReceipt; readonly createdAt: string; readonly state: 'upgrading-inactive'; readonly serviceRegistered: false; readonly externalEffectsEnabled: false }

/** Replaces only immutable program bytes while the prepared service is inactive. Tenant state, config and service identity stay untouched. */
export async function upgradeInactiveInstalledServerProgramV1(installRoot: string, distributionRoot: string, now = new Date()): Promise<InactiveServerProgramUpgradeReceiptV1> {
  const root = await exactRoot(installRoot); const prior = await recoverInactiveServerInstallation(root); const next = await verifyServerDistribution(distributionRoot)
  if (Number.isNaN(now.getTime()) || next.artifactDigest === prior.distributionDigest) throw new Error('server program upgrade input is invalid')
  const service = await recoverPreparedServerUserService(root); await assertInactive(root); await assertCompatibleTemplate(root, distributionRoot, service.platform)
  const rollback = join(root, 'rollback/previous'); const candidate = join(root, '.server-upgrade-candidate'); const priorProgram = join(root, '.server-upgrade-prior-program'); const priorManifest = join(root, '.server-upgrade-prior-manifest.json'); const intentPath = join(root, 'runtime/server-upgrade-intent.json')
  for (const path of [rollback, candidate, priorProgram, priorManifest, intentPath, `${join(root, 'install-receipt.json')}.tmp`]) await absent(path)
  await mkdir(join(root, 'rollback'), { mode: 0o700 }); await mkdir(rollback, { mode: 0o700 }); await copyServerDistribution(root, rollback, await verifyServerDistribution(root)); await verifyServerDistribution(rollback)
  await mkdir(candidate, { mode: 0o700 }); await copyServerDistribution(distributionRoot, candidate, next); await verifyServerDistribution(candidate)
  const intent: UpgradeIntentV1 = Object.freeze({ schemaVersion: 1, installationId: prior.installationId, priorReceipt: prior, createdAt: now.toISOString(), state: 'upgrading-inactive', serviceRegistered: false, externalEffectsEnabled: false }); await writeExclusive(intentPath, intent)
  try {
    await rename(join(root, 'program'), priorProgram); await rename(join(root, 'server-distribution.json'), priorManifest); await rename(join(candidate, 'program'), join(root, 'program')); await rename(join(candidate, 'server-distribution.json'), join(root, 'server-distribution.json'))
    const receipt = upgradedReceipt(prior, next, now); await replaceReceipt(root, receipt); await rm(priorProgram, { recursive: true }); await unlink(priorManifest); await rm(candidate, { recursive: true }); await recoverInactiveServerInstallation(root); await recoverPreparedServerUserService(root); await unlink(intentPath)
    return Object.freeze({ schemaVersion: 1, installationId: prior.installationId, fromVersion: prior.serverVersion, fromRevision: prior.sourceRevision, toVersion: next.serverVersion, toRevision: next.sourceRevision, upgradedAt: now.toISOString(), state: 'upgraded-inactive', rollbackPrepared: true, serviceRegistered: false, externalEffectsEnabled: false })
  } catch (error) { try { await reconcileInterruptedInactiveServerProgramUpgradeV1(root) } catch (rollbackError) { throw new AggregateError([error, rollbackError], 'server program upgrade failed and rollback is incomplete') }; throw error }
}

/** Restores the verified prior distribution after an interrupted or failed inactive upgrade. */
export async function reconcileInterruptedInactiveServerProgramUpgradeV1(installRoot: string): Promise<InactiveServerInstallationReceipt | null> {
  const root = await exactRoot(installRoot); const intentPath = join(root, 'runtime/server-upgrade-intent.json'); let intent: UpgradeIntentV1
  try { intent = exactIntent(JSON.parse(await readFile(intentPath, 'utf8'))) } catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null; throw error }
  await assertInactive(root); const rollback = join(root, 'rollback/previous'); const manifest = await verifyServerDistribution(rollback); if (manifest.artifactDigest !== intent.priorReceipt.distributionDigest || manifest.sourceRevision !== intent.priorReceipt.sourceRevision) throw new Error('server program rollback lineage drifted')
  for (const path of [join(root, 'program'), join(root, 'server-distribution.json'), join(root, '.server-upgrade-prior-program'), join(root, '.server-upgrade-prior-manifest.json'), join(root, '.server-upgrade-candidate')]) await rm(path, { recursive: true, force: true })
  await copyServerDistribution(rollback, root, manifest); await replaceReceipt(root, intent.priorReceipt); await rm(join(root, 'rollback'), { recursive: true }); await unlink(intentPath); await recoverInactiveServerInstallation(root); await recoverPreparedServerUserService(root); return intent.priorReceipt
}

/** Swaps back to the one verified previous release while retaining the current release as the next rollback target. */
export async function rollbackInactiveInstalledServerProgramV1(installRoot: string, now = new Date()): Promise<InactiveServerProgramUpgradeReceiptV1> {
  const root = await exactRoot(installRoot); const current = await recoverInactiveServerInstallation(root); if (current.schemaVersion !== 2) throw new Error('server program rollback is unavailable')
  await assertInactive(root); await recoverPreparedServerUserService(root); const previous = join(root, 'rollback/previous'); const manifest = await verifyServerDistribution(previous)
  if (manifest.serverVersion !== current.previous.serverVersion || manifest.sourceRevision !== current.previous.sourceRevision || manifest.artifactDigest !== current.previous.distributionDigest) throw new Error('server program rollback lineage drifted')
  const source = `${root}.rollback-source`; await absent(source); await rename(previous, source); await rm(join(root, 'rollback'), { recursive: true })
  try { const receipt = await upgradeInactiveInstalledServerProgramV1(root, source, now); await rm(source, { recursive: true }); return receipt }
  catch (error) { try { await lstat(join(root, 'rollback/previous')) } catch { await mkdir(join(root, 'rollback'), { mode: 0o700 }); await rename(source, join(root, 'rollback/previous')) }; throw error }
}

function upgradedReceipt(prior: InactiveServerInstallationReceipt, next: ServerDistributionManifestV1, now: Date): InactiveServerInstallationReceiptV2 { return Object.freeze({ schemaVersion: 2, installationId: prior.installationId, identityVersion: prior.schemaVersion === 2 ? prior.identityVersion : prior.serverVersion, serverVersion: next.serverVersion, distributionDigest: next.artifactDigest, sourceRevision: next.sourceRevision, installedAt: prior.installedAt, upgradedAt: now.toISOString(), previous: Object.freeze({ serverVersion: prior.serverVersion, distributionDigest: prior.distributionDigest, sourceRevision: prior.sourceRevision }), state: 'installed-inactive', configurationPresent: false, autoStart: false, serviceRegistered: false, sshGatewayApplied: false, externalEffectsEnabled: false }) }
async function assertInactive(root: string): Promise<void> { for (const name of ['activation-intent.json','activation-receipt.json','deactivation-intent.json']) try { await lstat(join(root, 'service', name)); throw new Error('server program upgrade requires an inactive service') } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error } }
async function assertCompatibleTemplate(root: string, distributionRoot: string, platform: 'launchd-user' | 'systemd-user'): Promise<void> { const relative = platform === 'launchd-user' ? 'program/deploy/launchd/com.quarkfan.quark-server.plist.template' : 'program/deploy/systemd/quark-server.service.template'; if (!Buffer.from(await readFile(join(root, relative))).equals(await readFile(join(distributionRoot, relative)))) throw new Error('server program upgrade changes the prepared service contract') }
async function replaceReceipt(root: string, receipt: InactiveServerInstallationReceipt): Promise<void> { const target = join(root, 'install-receipt.json'); const temporary = `${target}.tmp`; await rm(temporary, { force: true }); const handle = await open(temporary, 'wx', 0o600); try { await handle.writeFile(`${JSON.stringify(receipt)}\n`); await handle.sync() } finally { await handle.close() }; await rename(temporary, target); await chmod(target, 0o600) }
async function writeExclusive(path: string, value: unknown): Promise<void> { const handle = await open(path, 'wx', 0o600); try { await handle.writeFile(`${JSON.stringify(value)}\n`); await handle.sync() } finally { await handle.close() } }
async function exactRoot(value: string): Promise<string> { if (!isAbsolute(value) || resolve(value) !== value || value === '/' || await realpath(value) !== value) throw new Error('server program upgrade installation is invalid'); return value }
async function absent(path: string): Promise<void> { try { await lstat(path); throw new Error('server program upgrade workspace is not empty') } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error } }
function exactIntent(value: unknown): UpgradeIntentV1 { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('server program upgrade intent is invalid'); const item = value as Record<string, unknown>; if (Object.keys(item).sort().join(',') !== ['schemaVersion','installationId','priorReceipt','createdAt','state','serviceRegistered','externalEffectsEnabled'].sort().join(',') || item.schemaVersion !== 1 || typeof item.installationId !== 'string' || typeof item.createdAt !== 'string' || Number.isNaN(Date.parse(item.createdAt)) || item.state !== 'upgrading-inactive' || item.serviceRegistered !== false || item.externalEffectsEnabled !== false || !item.priorReceipt || typeof item.priorReceipt !== 'object') throw new Error('server program upgrade intent is invalid'); return item as unknown as UpgradeIntentV1 }
