import { createHash, createPrivateKey, createPublicKey, X509Certificate } from 'node:crypto'
import { chmod, copyFile, lstat, open, readFile, readdir, realpath, unlink } from 'node:fs/promises'
import { isIP } from 'node:net'
import { isAbsolute, join, resolve } from 'node:path'
import { NodePinnedEd25519PlanVerifierV1 } from '../client-runtime/plan-signature.js'
import { recoverInactiveServerInstallation } from './server-installation.js'

const digestPattern = /^sha256:[a-f0-9]{64}$/
export interface InactiveServerConfigurationInputV1 { readonly installRoot: string; readonly tlsKeySourcePath: string; readonly tlsCertSourcePath: string; readonly host: string; readonly port: number; readonly requestTimeoutMs: number; readonly maxConnections: number; readonly sshRequestTimeoutMs: number; readonly planVerification: { readonly keyId: string; readonly publicKey: string } }
export interface InactiveServerConfigurationReceiptV1 { readonly schemaVersion: 1; readonly installationId: string; readonly configDigest: string; readonly sshConfigDigest: string; readonly tlsKeyDigest: string; readonly tlsCertDigest: string; readonly configuredAt: string; readonly state: 'configured-inactive'; readonly databaseInitialized: false; readonly firstOwnerCreated: false; readonly serviceRegistered: false; readonly sshGatewayApplied: false; readonly autoStart: false; readonly externalEffectsEnabled: false }

/** Provisions private host config only. It does not initialize state, install a service or open a listener. */
export async function provisionInactiveServerConfiguration(input: InactiveServerConfigurationInputV1, now = new Date()): Promise<InactiveServerConfigurationReceiptV1> {
  const installRoot = await canonicalRoot(input.installRoot); const installation = await recoverInactiveServerInstallation(installRoot); validateInput(input, now)
  const configRoot = join(installRoot, 'config'); if ((await readdir(configRoot)).length) throw new Error('server configuration already exists')
  if ((await readdir(join(installRoot, 'runtime'))).length || (await readdir(join(installRoot, 'state'))).length) throw new Error('server configuration requires unused namespaces')
  const key = await privateSource(input.tlsKeySourcePath, 32_768); let cert: Buffer | undefined; const created: string[] = []
  try {
    cert = await privateSource(input.tlsCertSourcePath, 65_536); validateTlsPair(key, cert); new NodePinnedEd25519PlanVerifierV1(input.planVerification.keyId, input.planVerification.publicKey)
    const keyPath = join(configRoot, 'tls-key.pem'); const certPath = join(configRoot, 'tls-cert.pem'); const serverPath = join(configRoot, 'server.json'); const sshPath = join(configRoot, 'ssh.json')
    created.push(keyPath); await copyPrivate(input.tlsKeySourcePath, keyPath); created.push(certPath); await copyPrivate(input.tlsCertSourcePath, certPath)
    const migrations = Object.fromEntries(([['tenant','001_tenant_identity.sql'],['studio','002_agent_studio.sql'],['capability','003_capability_registry.sql'],['deviceSession','004_device_sessions.sql'],['deviceEnrollment','005_device_enrollment.sql'],['identity','006_cloud_identity.sql'],['identityAdministration','007_identity_administration.sql']] as const).map(([name, file]) => [name, join(installRoot, 'program/migrations/control-plane-sqlite', file)]))
    const socketPath = join(installRoot, 'runtime/device.sock'); const instanceLeasePath = join(installRoot, 'runtime/instance'); const databasePath = join(installRoot, 'state/control.sqlite3')
    const server = { schemaVersion: 1, runtime: { schemaVersion: 1, host: { schemaVersion: 1, composition: { schemaVersion: 1, databasePath, migrations, listenerEnabled: false, externalEffectsEnabled: false }, directTls: 'prepared-inactive', sshSubsystem: 'prepared-inactive', singleProvider: true, activationAllowed: false }, tls: { schemaVersion: 1, enabled: true, host: input.host, port: input.port, requestTimeoutMs: input.requestTimeoutMs, maxConnections: input.maxConnections, providerOwnership: 'shared-host', externalEffectsEnabled: false }, sshIpc: { schemaVersion: 1, enabled: true, socketPath, requestTimeoutMs: input.sshRequestTimeoutMs, providerOwnership: 'shared-host', externalEffectsEnabled: false }, singleProvider: true, externalEffectsEnabled: false }, instanceLeasePath, tlsCredentials: { keyPath, certPath }, planVerification: input.planVerification }
    const ssh = { schemaVersion: 1, socketPath, timeoutMs: input.sshRequestTimeoutMs, providerOwnership: 'shared-host', externalEffectsEnabled: false }
    const serverBytes = Buffer.from(`${JSON.stringify(server)}\n`); const sshBytes = Buffer.from(`${JSON.stringify(ssh)}\n`); created.push(serverPath); await writePrivate(serverPath, serverBytes); created.push(sshPath); await writePrivate(sshPath, sshBytes)
    const receipt = Object.freeze({ schemaVersion: 1 as const, installationId: installation.installationId, configDigest: digest(serverBytes), sshConfigDigest: digest(sshBytes), tlsKeyDigest: digest(key), tlsCertDigest: digest(cert), configuredAt: now.toISOString(), state: 'configured-inactive' as const, databaseInitialized: false as const, firstOwnerCreated: false as const, serviceRegistered: false as const, sshGatewayApplied: false as const, autoStart: false as const, externalEffectsEnabled: false as const })
    const receiptPath = join(configRoot, 'configuration-receipt.json'); created.push(receiptPath); await writePrivate(receiptPath, Buffer.from(`${JSON.stringify(receipt)}\n`)); return receipt
  } catch (error) { for (const path of created.reverse()) { try { await unlink(path) } catch {} }; throw error }
  finally { key.fill(0); cert?.fill(0) }
}

/** Verifies configured bytes without opening a database or listener. */
export async function recoverInactiveServerConfiguration(installRootValue: string): Promise<InactiveServerConfigurationReceiptV1> {
  const root = await canonicalRoot(installRootValue); const installation = await recoverInactiveServerInstallation(root); const configRoot = join(root, 'config')
  if ((await readdir(configRoot)).sort().join(',') !== 'configuration-receipt.json,server.json,ssh.json,tls-cert.pem,tls-key.pem') throw new Error('server configuration layout is invalid')
  const [receiptBytes, serverBytes, sshBytes, key, cert] = await Promise.all([readPrivate(join(configRoot, 'configuration-receipt.json'), 64 * 1024), readPrivate(join(configRoot, 'server.json'), 64 * 1024), readPrivate(join(configRoot, 'ssh.json'), 16 * 1024), readPrivate(join(configRoot, 'tls-key.pem'), 32_768), readPrivate(join(configRoot, 'tls-cert.pem'), 65_536)])
  try { const receipt = exactReceipt(JSON.parse(receiptBytes.toString('utf8'))); if (receipt.installationId !== installation.installationId || receipt.configDigest !== digest(serverBytes) || receipt.sshConfigDigest !== digest(sshBytes) || receipt.tlsKeyDigest !== digest(key) || receipt.tlsCertDigest !== digest(cert)) throw new Error('server configuration digest drifted'); validateStoredConfiguration(root, serverBytes, sshBytes); validateTlsPair(key, cert); return receipt }
  catch (error) { if (error instanceof SyntaxError) throw new Error('server configuration receipt is invalid'); throw error }
  finally { key.fill(0); cert.fill(0) }
}

/** Removes only unchanged configuration before database/runtime/service creation. */
export async function removeUnusedServerConfiguration(installRootValue: string): Promise<InactiveServerConfigurationReceiptV1> { const root = await canonicalRoot(installRootValue); const receipt = await recoverInactiveServerConfiguration(root); if ((await readdir(join(root, 'runtime'))).length || (await readdir(join(root, 'state'))).length) throw new Error('server configuration has runtime or durable state'); for (const name of ['configuration-receipt.json','server.json','ssh.json','tls-cert.pem','tls-key.pem']) await unlink(join(root, 'config', name)); return receipt }

function validateInput(input: InactiveServerConfigurationInputV1, now: Date): void { if (!input || typeof input !== 'object' || !input.planVerification || typeof input.planVerification !== 'object' || typeof input.planVerification.keyId !== 'string' || typeof input.planVerification.publicKey !== 'string' || !isIP(input.host) || !Number.isSafeInteger(input.port) || input.port < 1 || input.port > 65535 || !bounded(input.requestTimeoutMs, 1_000, 30_000) || !bounded(input.sshRequestTimeoutMs, 1_000, 30_000) || !bounded(input.maxConnections, 1, 10_000) || Number.isNaN(now.getTime())) throw new Error('server configuration input is invalid') }
function bounded(value: number, min: number, max: number): boolean { return Number.isSafeInteger(value) && value >= min && value <= max }
async function canonicalRoot(value: string): Promise<string> { if (!isAbsolute(value) || resolve(value) !== value || await realpath(value) !== value) throw new Error('server configuration root is invalid'); return value }
async function privateSource(path: string, max: number): Promise<Buffer> { if (!isAbsolute(path) || resolve(path) !== path) throw new Error('server TLS source is invalid'); return await readPrivate(path, max) }
async function readPrivate(path: string, max: number): Promise<Buffer> { const state = await lstat(path); const uid = process.getuid?.(); if (!state.isFile() || state.isSymbolicLink() || state.nlink !== 1 || (state.mode & 0o077) !== 0 || state.size <= 0 || state.size > max || await realpath(path) !== path || (uid !== undefined && state.uid !== uid)) throw new Error('server configuration file is unsafe'); return await readFile(path) }
async function copyPrivate(source: string, destination: string): Promise<void> { await copyFile(source, destination); await chmod(destination, 0o600) }
async function writePrivate(path: string, bytes: Uint8Array): Promise<void> { const handle = await open(path, 'wx', 0o600); try { await handle.writeFile(bytes); await handle.sync() } finally { await handle.close() } }
function validateTlsPair(keyBytes: Buffer, certBytes: Buffer): void { try { const key = createPrivateKey(keyBytes); const cert = new X509Certificate(certBytes); const first = createPublicKey(key).export({ format: 'der', type: 'spki' }) as Buffer; const second = cert.publicKey.export({ format: 'der', type: 'spki' }) as Buffer; if (!first.equals(second)) throw new Error('mismatch') } catch { throw new Error('server TLS credential pair is invalid') } }
function validateStoredConfiguration(root: string, serverBytes: Buffer, sshBytes: Buffer): void {
  try {
    const server = JSON.parse(serverBytes.toString('utf8')) as unknown; const ssh = JSON.parse(sshBytes.toString('utf8')) as unknown
    if (!isRecord(server) || !exactKeys(server, ['schemaVersion','runtime','instanceLeasePath','tlsCredentials','planVerification']) || server.schemaVersion !== 1 || server.instanceLeasePath !== join(root, 'runtime/instance') || !isRecord(server.runtime) || !isRecord(server.tlsCredentials) || !isRecord(server.planVerification)) throw new Error('invalid')
    const runtime = server.runtime; if (!exactKeys(runtime, ['schemaVersion','host','tls','sshIpc','singleProvider','externalEffectsEnabled']) || runtime.schemaVersion !== 1 || runtime.singleProvider !== true || runtime.externalEffectsEnabled !== false || !isRecord(runtime.host) || !isRecord(runtime.tls) || !isRecord(runtime.sshIpc)) throw new Error('invalid')
    const host = runtime.host; if (!exactKeys(host, ['schemaVersion','composition','directTls','sshSubsystem','singleProvider','activationAllowed']) || host.schemaVersion !== 1 || host.directTls !== 'prepared-inactive' || host.sshSubsystem !== 'prepared-inactive' || host.singleProvider !== true || host.activationAllowed !== false || !isRecord(host.composition)) throw new Error('invalid')
    const composition = host.composition; if (!exactKeys(composition, ['schemaVersion','databasePath','migrations','listenerEnabled','externalEffectsEnabled']) || composition.schemaVersion !== 1 || composition.databasePath !== join(root, 'state/control.sqlite3') || composition.listenerEnabled !== false || composition.externalEffectsEnabled !== false || !isRecord(composition.migrations)) throw new Error('invalid')
    const migrations = composition.migrations as Record<string, unknown>; const migrationNames = { tenant: '001_tenant_identity.sql', studio: '002_agent_studio.sql', capability: '003_capability_registry.sql', deviceSession: '004_device_sessions.sql', deviceEnrollment: '005_device_enrollment.sql', identity: '006_cloud_identity.sql', identityAdministration: '007_identity_administration.sql' } as const
    if (!exactKeys(migrations, Object.keys(migrationNames)) || Object.entries(migrationNames).some(([name, file]) => migrations[name] !== join(root, 'program/migrations/control-plane-sqlite', file))) throw new Error('invalid')
    const tls = runtime.tls; if (!exactKeys(tls, ['schemaVersion','enabled','host','port','requestTimeoutMs','maxConnections','providerOwnership','externalEffectsEnabled']) || tls.schemaVersion !== 1 || tls.enabled !== true || typeof tls.host !== 'string' || !isIP(tls.host) || !bounded(tls.port as number, 1, 65535) || !bounded(tls.requestTimeoutMs as number, 1_000, 30_000) || !bounded(tls.maxConnections as number, 1, 10_000) || tls.providerOwnership !== 'shared-host' || tls.externalEffectsEnabled !== false) throw new Error('invalid')
    const ipc = runtime.sshIpc; const socketPath = join(root, 'runtime/device.sock'); if (!exactKeys(ipc, ['schemaVersion','enabled','socketPath','requestTimeoutMs','providerOwnership','externalEffectsEnabled']) || ipc.schemaVersion !== 1 || ipc.enabled !== true || ipc.socketPath !== socketPath || !bounded(ipc.requestTimeoutMs as number, 1_000, 30_000) || ipc.providerOwnership !== 'shared-host' || ipc.externalEffectsEnabled !== false) throw new Error('invalid')
    if (!exactKeys(server.tlsCredentials, ['keyPath','certPath']) || server.tlsCredentials.keyPath !== join(root, 'config/tls-key.pem') || server.tlsCredentials.certPath !== join(root, 'config/tls-cert.pem') || !exactKeys(server.planVerification, ['keyId','publicKey']) || typeof server.planVerification.keyId !== 'string' || typeof server.planVerification.publicKey !== 'string') throw new Error('invalid')
    new NodePinnedEd25519PlanVerifierV1(server.planVerification.keyId, server.planVerification.publicKey)
    if (!isRecord(ssh) || !exactKeys(ssh, ['schemaVersion','socketPath','timeoutMs','providerOwnership','externalEffectsEnabled']) || ssh.schemaVersion !== 1 || ssh.socketPath !== socketPath || ssh.timeoutMs !== ipc.requestTimeoutMs || ssh.providerOwnership !== 'shared-host' || ssh.externalEffectsEnabled !== false) throw new Error('invalid')
  } catch { throw new Error('server configuration content is invalid') }
}
function isRecord(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === 'object' && !Array.isArray(value) }
function exactKeys(value: Record<string, unknown>, keys: readonly string[]): boolean { return Object.keys(value).sort().join(',') === [...keys].sort().join(',') }
function digest(bytes: Uint8Array): string { return `sha256:${createHash('sha256').update(bytes).digest('hex')}` }
function exactReceipt(value: unknown): InactiveServerConfigurationReceiptV1 { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('server configuration receipt is invalid'); const item = value as Record<string, unknown>; const keys = ['schemaVersion','installationId','configDigest','sshConfigDigest','tlsKeyDigest','tlsCertDigest','configuredAt','state','databaseInitialized','firstOwnerCreated','serviceRegistered','sshGatewayApplied','autoStart','externalEffectsEnabled']; if (Object.keys(item).sort().join(',') !== keys.sort().join(',') || item.schemaVersion !== 1 || typeof item.installationId !== 'string' || !/^server-installation\.[a-f0-9]{32}$/.test(item.installationId) || ['configDigest','sshConfigDigest','tlsKeyDigest','tlsCertDigest'].some(name => typeof item[name] !== 'string' || !digestPattern.test(item[name] as string)) || typeof item.configuredAt !== 'string' || Number.isNaN(Date.parse(item.configuredAt)) || item.state !== 'configured-inactive' || item.databaseInitialized !== false || item.firstOwnerCreated !== false || item.serviceRegistered !== false || item.sshGatewayApplied !== false || item.autoStart !== false || item.externalEffectsEnabled !== false) throw new Error('server configuration receipt is invalid'); return Object.freeze(item as unknown as InactiveServerConfigurationReceiptV1) }
