import { createHash } from 'node:crypto'
import { lstat, open, readdir, readFile, realpath } from 'node:fs/promises'
import { isAbsolute, relative, resolve, sep } from 'node:path'

const digestPattern = /^sha256:[a-f0-9]{64}$/
const revisionPattern = /^[a-f0-9]{40}$/
const versionPattern = /^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?$/
export interface ServerDistributionFileV1 { readonly path: string; readonly size: number; readonly digest: string }
export interface ServerDistributionManifestV1 { readonly schemaVersion: 1; readonly serverVersion: string; readonly sourceRevision: string; readonly serverEntrypoint: 'program/dist/control-plane/cloud-server-entry.js'; readonly adminEntrypoint: 'program/dist/control-plane/server-admin-entry.js'; readonly sshEntrypoint: 'program/dist/client-runtime/ssh-subsystem-entry.js'; readonly launchdTemplate: 'program/deploy/launchd/com.quarkfan.quark-server.plist.template'; readonly systemdTemplate: 'program/deploy/systemd/quark-server.service.template'; readonly sbomPath: 'program/sbom.spdx.json'; readonly files: readonly ServerDistributionFileV1[]; readonly artifactDigest: string; readonly autoStart: false; readonly sshGatewayApplied: false; readonly externalEffectsEnabled: false }

/** Seals a preassembled, host-neutral server program. It contains no tenant state, credentials or deployment config. */
export async function sealServerDistribution(root: string, serverVersion: string, sourceRevision: string): Promise<ServerDistributionManifestV1> {
  const canonical = await privateCanonicalDirectory(root)
  if (!versionPattern.test(serverVersion) || !revisionPattern.test(sourceRevision)) throw new Error('server distribution identity is invalid')
  if ((await readdir(canonical)).includes('server-distribution.json')) throw new Error('server distribution is already sealed')
  const files = await inventory(canonical); requireFiles(files)
  const unsigned = { schemaVersion: 1 as const, serverVersion, sourceRevision, serverEntrypoint: 'program/dist/control-plane/cloud-server-entry.js' as const, adminEntrypoint: 'program/dist/control-plane/server-admin-entry.js' as const, sshEntrypoint: 'program/dist/client-runtime/ssh-subsystem-entry.js' as const, launchdTemplate: 'program/deploy/launchd/com.quarkfan.quark-server.plist.template' as const, systemdTemplate: 'program/deploy/systemd/quark-server.service.template' as const, sbomPath: 'program/sbom.spdx.json' as const, files, autoStart: false as const, sshGatewayApplied: false as const, externalEffectsEnabled: false as const }
  const manifest = Object.freeze({ ...unsigned, artifactDigest: digest(Buffer.from(JSON.stringify(unsigned), 'utf8')) })
  const handle = await open(resolve(canonical, 'server-distribution.json'), 'wx', 0o600)
  try { await handle.writeFile(`${JSON.stringify(manifest)}\n`); await handle.sync() } finally { await handle.close() }
  return manifest
}

/** Recomputes the complete private inventory before a future installer may consume it. */
export async function verifyServerDistribution(root: string): Promise<ServerDistributionManifestV1> {
  const canonical = await privateCanonicalDirectory(root)
  const top = (await readdir(canonical)).sort().join(',')
  if (!['program,server-distribution.json', 'config,install-receipt.json,program,runtime,server-distribution.json,service,state'].includes(top)) throw new Error('server distribution layout is invalid')
  const bytes = await boundedPrivateFile(resolve(canonical, 'server-distribution.json'), 16 * 1024 * 1024)
  let parsed: unknown; try { parsed = JSON.parse(bytes.toString('utf8')) } catch { throw new Error('server distribution manifest is invalid') }
  const manifest = exactManifest(parsed); const actual = await inventory(canonical)
  if (JSON.stringify(actual) !== JSON.stringify(manifest.files)) throw new Error('server distribution inventory drifted')
  requireFiles(actual); const { artifactDigest, ...unsigned } = manifest
  if (digest(Buffer.from(JSON.stringify(unsigned), 'utf8')) !== artifactDigest) throw new Error('server distribution digest drifted')
  return manifest
}

async function inventory(root: string): Promise<readonly ServerDistributionFileV1[]> { const output: ServerDistributionFileV1[] = []; async function visit(directory: string): Promise<void> { for (const name of (await readdir(directory)).sort()) { const path = resolve(directory, name); const status = await lstat(path); if (status.isSymbolicLink()) throw new Error('server distribution cannot contain links'); if (status.isDirectory()) { if ((status.mode & 0o077) !== 0) throw new Error('server distribution directory must be private'); await visit(path); continue }; if (!status.isFile() || (status.mode & 0o077) !== 0 || status.size <= 0 || status.size > 64 * 1024 * 1024) throw new Error('server distribution file is unsafe'); const bytes = await readFile(path); output.push(Object.freeze({ path: portable(root, path), size: bytes.byteLength, digest: digest(bytes) })) } }; await visit(resolve(root, 'program')); return Object.freeze(output.sort((a, b) => a.path.localeCompare(b.path))) }
function requireFiles(files: readonly ServerDistributionFileV1[]): void { const paths = new Set(files.map(file => file.path)); for (const required of ['program/dist/control-plane/cloud-server-entry.js', 'program/dist/control-plane/server-admin-entry.js', 'program/dist/client-runtime/ssh-subsystem-entry.js', 'program/deploy/launchd/com.quarkfan.quark-server.plist.template', 'program/deploy/systemd/quark-server.service.template', 'program/package.json', 'program/sbom.spdx.json', ...['001_tenant_identity.sql','002_agent_studio.sql','003_capability_registry.sql','004_device_sessions.sql','005_device_enrollment.sql','006_cloud_identity.sql','007_identity_administration.sql'].map(name => `program/migrations/control-plane-sqlite/${name}`)]) if (!paths.has(required)) throw new Error(`server distribution is incomplete: ${required}`) }
function exactManifest(value: unknown): ServerDistributionManifestV1 { if (!isRecord(value)) throw new Error('server distribution manifest is invalid'); const keys = ['schemaVersion','serverVersion','sourceRevision','serverEntrypoint','adminEntrypoint','sshEntrypoint','launchdTemplate','systemdTemplate','sbomPath','files','artifactDigest','autoStart','sshGatewayApplied','externalEffectsEnabled']; if (Object.keys(value).sort().join(',') !== keys.sort().join(',') || value.schemaVersion !== 1 || typeof value.serverVersion !== 'string' || !versionPattern.test(value.serverVersion) || typeof value.sourceRevision !== 'string' || !revisionPattern.test(value.sourceRevision) || value.serverEntrypoint !== 'program/dist/control-plane/cloud-server-entry.js' || value.adminEntrypoint !== 'program/dist/control-plane/server-admin-entry.js' || value.sshEntrypoint !== 'program/dist/client-runtime/ssh-subsystem-entry.js' || value.launchdTemplate !== 'program/deploy/launchd/com.quarkfan.quark-server.plist.template' || value.systemdTemplate !== 'program/deploy/systemd/quark-server.service.template' || value.sbomPath !== 'program/sbom.spdx.json' || typeof value.artifactDigest !== 'string' || !digestPattern.test(value.artifactDigest) || value.autoStart !== false || value.sshGatewayApplied !== false || value.externalEffectsEnabled !== false || !Array.isArray(value.files)) throw new Error('server distribution manifest is invalid'); let prior = ''; for (const raw of value.files as unknown[]) { if (!isRecord(raw) || Object.keys(raw).sort().join(',') !== 'digest,path,size' || typeof raw.path !== 'string' || !safeRelative(raw.path) || (prior && raw.path.localeCompare(prior) <= 0) || !Number.isSafeInteger(raw.size) || (raw.size as number) <= 0 || typeof raw.digest !== 'string' || !digestPattern.test(raw.digest)) throw new Error('server distribution file record is invalid'); prior = raw.path }; return Object.freeze(value as unknown as ServerDistributionManifestV1) }
async function privateCanonicalDirectory(value: string): Promise<string> { if (!isAbsolute(value) || resolve(value) !== value || value === '/' || await realpath(value) !== value) throw new Error('server distribution root must be canonical'); const state = await lstat(value); if (!state.isDirectory() || state.isSymbolicLink() || (state.mode & 0o077) !== 0) throw new Error('server distribution root must be private'); return value }
async function boundedPrivateFile(path: string, max: number): Promise<Buffer> { const state = await lstat(path); if (!state.isFile() || state.isSymbolicLink() || state.nlink !== 1 || (state.mode & 0o077) !== 0 || state.size <= 0 || state.size > max) throw new Error('server distribution manifest is unsafe'); return await readFile(path) }
function portable(root: string, path: string): string { const value = relative(root, path).split(sep).join('/'); if (!safeRelative(value)) throw new Error('server distribution path is unsafe'); return value }
function safeRelative(value: string): boolean { return Boolean(value) && !value.startsWith('/') && !value.includes('\\') && value.split('/').every(part => part && part !== '.' && part !== '..') }
function digest(value: Uint8Array): string { return `sha256:${createHash('sha256').update(value).digest('hex')}` }
function isRecord(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === 'object' && !Array.isArray(value) }
