import { DatabaseSync } from 'node:sqlite'
import { lstat, open, readFile, readdir, realpath } from 'node:fs/promises'
import { isAbsolute, join, resolve } from 'node:path'
import { bootstrapFirstCloudOwnerV1 } from './cloud-owner-bootstrap.js'
import { recoverInactiveServerConfiguration } from './server-configuration.js'

export interface InstalledFirstOwnerInputV1 { readonly installRoot: string; readonly tenantId: string; readonly tenantName: string; readonly userId: string; readonly displayName: string }
export interface InstalledFirstOwnerReceiptRepairV1 { readonly installRoot: string; readonly tenantId: string; readonly userId: string }
export interface InstalledFirstOwnerReceiptV1 { readonly schemaVersion: 1; readonly installationId: string; readonly configurationDigest: string; readonly tenantId: string; readonly userId: string; readonly state: 'owner-created-inactive'; readonly roles: readonly ['owner']; readonly createdAt: string; readonly identityDatabaseInitialized: true; readonly passwordRetained: false; readonly sessionCreated: false; readonly serviceRegistered: false; readonly sshGatewayApplied: false; readonly autoStart: false; readonly externalEffectsEnabled: false }

/** Creates the first cloud owner inside one configured installation without starting its server. */
export async function bootstrapInstalledFirstOwner(input: InstalledFirstOwnerInputV1, password: string, now = new Date()): Promise<InstalledFirstOwnerReceiptV1> {
  const root = await canonicalRoot(input.installRoot); const configuration = await recoverInactiveServerConfiguration(root); validateInput(input)
  if ((await readdir(join(root, 'runtime'))).length || (await readdir(join(root, 'state'))).length) throw new Error('installed owner bootstrap requires unused runtime and state')
  const result = await bootstrapFirstCloudOwnerV1({ schemaVersion: 1, databasePath: join(root, 'state/control.sqlite3'), tenantMigrationPath: join(root, 'program/migrations/control-plane-sqlite/001_tenant_identity.sql'), identityMigrationPath: join(root, 'program/migrations/control-plane-sqlite/006_cloud_identity.sql'), tenantId: input.tenantId, tenantName: input.tenantName, userId: input.userId, displayName: input.displayName }, password, now)
  await sealInactiveDatabase(join(root, 'state/control.sqlite3'))
  const receipt = Object.freeze({ schemaVersion: 1 as const, installationId: configuration.installationId, configurationDigest: configuration.configDigest, tenantId: result.tenantId, userId: result.userId, state: 'owner-created-inactive' as const, roles: Object.freeze(['owner'] as const), createdAt: result.createdAt, identityDatabaseInitialized: true as const, passwordRetained: false as const, sessionCreated: false as const, serviceRegistered: false as const, sshGatewayApplied: false as const, autoStart: false as const, externalEffectsEnabled: false as const })
  await writeExclusive(join(root, 'state/owner-bootstrap-receipt.json'), Buffer.from(`${JSON.stringify(receipt)}\n`)); return receipt
}

/** Reads the singleton owner and integrity-checks its database without authenticating or starting a listener. */
export async function recoverInstalledFirstOwner(installRootValue: string): Promise<InstalledFirstOwnerReceiptV1> {
  const root = await canonicalRoot(installRootValue); const configuration = await recoverInactiveServerConfiguration(root)
  if ((await readdir(join(root, 'runtime'))).length || (await readdir(join(root, 'state'))).sort().join(',') !== 'control.sqlite3,owner-bootstrap-receipt.json') throw new Error('installed owner bootstrap layout is invalid')
  const receipt = exactReceipt(JSON.parse((await readPrivate(join(root, 'state/owner-bootstrap-receipt.json'), 32 * 1024)).toString('utf8')))
  if (receipt.installationId !== configuration.installationId || receipt.configurationDigest !== configuration.configDigest) throw new Error('installed owner bootstrap lineage drifted')
  const owner = await inspectInstalledFirstOwnerDatabase(join(root, 'state/control.sqlite3')); if (owner.tenantId !== receipt.tenantId || owner.userId !== receipt.userId || owner.createdAt !== receipt.createdAt) throw new Error('installed owner bootstrap database is invalid')
  return receipt
}

/** Repairs only a missing receipt after the singleton database transaction succeeded. */
export async function repairInstalledFirstOwnerReceipt(input: InstalledFirstOwnerReceiptRepairV1): Promise<InstalledFirstOwnerReceiptV1> {
  if (!input || typeof input !== 'object' || Object.keys(input).sort().join(',') !== ['installRoot','tenantId','userId'].sort().join(',') || typeof input.tenantId !== 'string' || typeof input.userId !== 'string') throw new Error('installed owner receipt repair input is invalid')
  const root = await canonicalRoot(input.installRoot); const configuration = await recoverInactiveServerConfiguration(root)
  if ((await readdir(join(root, 'runtime'))).length || (await readdir(join(root, 'state'))).sort().join(',') !== 'control.sqlite3') throw new Error('installed owner receipt repair layout is invalid')
  const owner = await inspectInstalledFirstOwnerDatabase(join(root, 'state/control.sqlite3')); if (owner.tenantId !== input.tenantId || owner.userId !== input.userId) throw new Error('installed owner receipt repair identity is invalid')
  const receipt = Object.freeze({ schemaVersion: 1 as const, installationId: configuration.installationId, configurationDigest: configuration.configDigest, tenantId: owner.tenantId, userId: owner.userId, state: 'owner-created-inactive' as const, roles: Object.freeze(['owner'] as const), createdAt: owner.createdAt, identityDatabaseInitialized: true as const, passwordRetained: false as const, sessionCreated: false as const, serviceRegistered: false as const, sshGatewayApplied: false as const, autoStart: false as const, externalEffectsEnabled: false as const })
  await writeExclusive(join(root, 'state/owner-bootstrap-receipt.json'), Buffer.from(`${JSON.stringify(receipt)}\n`)); return receipt
}

function validateInput(input: InstalledFirstOwnerInputV1): void { if (!input || typeof input !== 'object' || Object.keys(input).sort().join(',') !== ['installRoot','tenantId','tenantName','userId','displayName'].sort().join(',') || ![input.tenantId,input.tenantName,input.userId,input.displayName].every(value => typeof value === 'string')) throw new Error('installed owner bootstrap input is invalid') }
async function canonicalRoot(value: string): Promise<string> { if (!isAbsolute(value) || resolve(value) !== value || await realpath(value) !== value) throw new Error('installed owner bootstrap root is invalid'); return value }
async function assertPrivateDatabase(path: string): Promise<void> { const state = await lstat(path); const uid = process.getuid?.(); if (!state.isFile() || state.isSymbolicLink() || state.nlink !== 1 || (state.mode & 0o077) !== 0 || await realpath(path) !== path || (uid !== undefined && state.uid !== uid)) throw new Error('installed owner bootstrap database is unsafe') }
async function sealInactiveDatabase(path: string): Promise<void> { await assertPrivateDatabase(path); const database = new DatabaseSync(path); try { database.exec('PRAGMA wal_checkpoint(TRUNCATE)'); const mode = database.prepare('PRAGMA journal_mode=DELETE').get() as { journal_mode?: string }; if (mode.journal_mode !== 'delete') throw new Error('installed owner bootstrap database could not enter inactive mode') } finally { database.close() } }
/** Verifies the exact singleton-owner state required by inactive install recovery. */
export async function inspectInstalledFirstOwnerDatabase(path: string): Promise<{ tenantId: string; userId: string; createdAt: string }> { await assertPrivateDatabase(path); const database = new DatabaseSync(path, { readOnly: true }); try { const integrity = database.prepare('PRAGMA integrity_check').get() as { integrity_check?: string }; const row = database.prepare("SELECT t.tenant_id AS tenantId, u.user_id AS userId, a.roles_json AS roles, t.state AS tenantState, u.state AS userState, a.state AS accountState, t.created_at AS tenantCreatedAt, u.created_at AS userCreatedAt, a.created_at AS accountCreatedAt, (SELECT COUNT(*) FROM cp_tenant) AS tenants, (SELECT COUNT(*) FROM cp_user) AS users, (SELECT COUNT(*) FROM cp_auth_account) AS accounts, (SELECT COUNT(*) FROM cp_browser_session) AS sessions FROM cp_tenant t JOIN cp_user u ON u.tenant_id=t.tenant_id JOIN cp_auth_account a ON a.tenant_id=u.tenant_id AND a.user_id=u.user_id").get() as Record<string, unknown> | undefined; if (integrity.integrity_check !== 'ok' || !row || typeof row.tenantId !== 'string' || typeof row.userId !== 'string' || typeof row.tenantCreatedAt !== 'string' || row.tenantCreatedAt !== row.userCreatedAt || row.tenantCreatedAt !== row.accountCreatedAt || Number.isNaN(Date.parse(row.tenantCreatedAt)) || row.roles !== '["owner"]' || row.tenantState !== 'active' || row.userState !== 'active' || row.accountState !== 'active' || row.tenants !== 1 || row.users !== 1 || row.accounts !== 1 || row.sessions !== 0) throw new Error('installed owner bootstrap database is invalid'); return { tenantId: row.tenantId, userId: row.userId, createdAt: row.tenantCreatedAt } } finally { database.close() } }
async function readPrivate(path: string, max: number): Promise<Buffer> { const state = await lstat(path); const uid = process.getuid?.(); if (!state.isFile() || state.isSymbolicLink() || state.nlink !== 1 || (state.mode & 0o077) !== 0 || state.size <= 0 || state.size > max || await realpath(path) !== path || (uid !== undefined && state.uid !== uid)) throw new Error('installed owner bootstrap file is unsafe'); return await readFile(path) }
async function writeExclusive(path: string, bytes: Uint8Array): Promise<void> { const handle = await open(path, 'wx', 0o600); try { await handle.writeFile(bytes); await handle.sync() } finally { await handle.close() } }
function exactReceipt(value: unknown): InstalledFirstOwnerReceiptV1 { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('installed owner bootstrap receipt is invalid'); const item = value as Record<string, unknown>; const keys = ['schemaVersion','installationId','configurationDigest','tenantId','userId','state','roles','createdAt','identityDatabaseInitialized','passwordRetained','sessionCreated','serviceRegistered','sshGatewayApplied','autoStart','externalEffectsEnabled']; if (Object.keys(item).sort().join(',') !== keys.sort().join(',') || item.schemaVersion !== 1 || typeof item.installationId !== 'string' || !/^server-installation\.[a-f0-9]{32}$/.test(item.installationId) || typeof item.configurationDigest !== 'string' || !/^sha256:[a-f0-9]{64}$/.test(item.configurationDigest) || typeof item.tenantId !== 'string' || typeof item.userId !== 'string' || item.state !== 'owner-created-inactive' || !Array.isArray(item.roles) || item.roles.length !== 1 || item.roles[0] !== 'owner' || typeof item.createdAt !== 'string' || Number.isNaN(Date.parse(item.createdAt)) || item.identityDatabaseInitialized !== true || item.passwordRetained !== false || item.sessionCreated !== false || item.serviceRegistered !== false || item.sshGatewayApplied !== false || item.autoStart !== false || item.externalEffectsEnabled !== false) throw new Error('installed owner bootstrap receipt is invalid'); return Object.freeze({ ...(item as unknown as InstalledFirstOwnerReceiptV1), roles: Object.freeze(['owner'] as const) }) }
