import { createHash } from 'node:crypto'
import { constants } from 'node:fs'
import { chmod, copyFile, lstat, mkdir, mkdtemp, open, readFile, readdir, realpath, rm } from 'node:fs/promises'
import { backup, DatabaseSync } from 'node:sqlite'
import { dirname, isAbsolute, join, resolve } from 'node:path'
import { recoverInactiveServerConfiguration } from './server-configuration.js'
import { recoverInactiveServerInstallation } from './server-installation.js'
import { inspectInstalledFirstOwnerDatabase, recoverInstalledFirstOwner, repairInstalledFirstOwnerReceipt } from './server-owner-bootstrap.js'
import { runServerRecoveryProcess } from './server-recovery-process.js'

const ageHeader = 'age-encryption.org/v1\n'
const digestPattern = /^sha256:[a-f0-9]{64}$/

export interface ServerStateRecoveryBinariesV1 { readonly age?: string; readonly tar?: string }
export interface CreateInactiveServerStateBundleInputV1 { readonly installRoot: string; readonly outputPath: string; readonly recipient: string; readonly binaries?: ServerStateRecoveryBinariesV1 }
export interface StageInactiveServerStateBundleInputV1 { readonly inputPath: string; readonly outputDirectory: string; readonly identityFile: string; readonly binaries?: ServerStateRecoveryBinariesV1 }
export interface PrepareInactiveServerStateRestoreInputV1 { readonly stagingDirectory: string; readonly installRoot: string }
export interface InactiveServerStateBundleV1 { readonly bundleFormatVersion: 1; readonly projectId: 'quarkselfai-server'; readonly bundleId: string; readonly createdAt: string; readonly captureMode: 'sqlite-online-backup'; readonly serverVersion: string; readonly sourceRevision: string; readonly distributionDigest: string; readonly sourceInstallationId: string; readonly owner: { readonly tenantId: string; readonly userId: string; readonly createdAt: string }; readonly entries: readonly [{ readonly path: 'state/control.sqlite3'; readonly bytes: number; readonly sha256: string }]; readonly restorePolicy: { readonly requiresFreshInactiveInstallation: true; readonly configurationRestored: false; readonly serviceRegistered: false; readonly sshGatewayApplied: false; readonly autoStart: false; readonly externalEffectsEnabled: false } }
export interface InactiveServerStateRestoreReceiptV1 { readonly schemaVersion: 1; readonly bundleId: string; readonly installationId: string; readonly state: 'owner-restored-inactive'; readonly serviceRegistered: false; readonly sshGatewayApplied: false; readonly autoStart: false; readonly externalEffectsEnabled: false }

/** Encrypts one verified server database without copying host paths, TLS material or runtime state. */
export async function createInactiveServerStateBundle(input: CreateInactiveServerStateBundleInputV1, now = new Date()): Promise<InactiveServerStateBundleV1> {
  const root = await canonicalDirectory(input.installRoot, 'server state backup root'); const output = await exactNewPath(input.outputPath, '.age'); validateRecipient(input.recipient)
  if (Number.isNaN(now.getTime())) throw new Error('server state backup timestamp is invalid')
  const installation = await recoverInactiveServerInstallation(root); await recoverInactiveServerConfiguration(root); const owner = await recoverInstalledFirstOwner(root)
  const binaries = { age: input.binaries?.age ?? 'age', tar: input.binaries?.tar ?? 'tar' }; await mkdir(dirname(output), { recursive: true, mode: 0o700 }); await canonicalDirectory(dirname(output), 'server state output parent')
  const temporary = await mkdtemp(join(dirname(output), '.quark-server-backup-')); await chmod(temporary, 0o700)
  let outputCreated = false
  try {
    const bundleRoot = join(temporary, 'bundle'); const stateRoot = join(bundleRoot, 'state'); const databasePath = join(stateRoot, 'control.sqlite3'); const archivePath = join(temporary, 'bundle.tar.gz'); const encryptedPath = join(temporary, 'bundle.age')
    await mkdir(stateRoot, { recursive: true, mode: 0o700 }); const source = new DatabaseSync(join(root, 'state/control.sqlite3'), { readOnly: true })
    try { await backup(source, databasePath) } finally { source.close() }
    await chmod(databasePath, 0o600); const snapshotOwner = await inspectInstalledFirstOwnerDatabase(databasePath); if (snapshotOwner.tenantId !== owner.tenantId || snapshotOwner.userId !== owner.userId || snapshotOwner.createdAt !== owner.createdAt) throw new Error('server state snapshot owner lineage drifted')
    const bytes = await readFile(databasePath); const entry = Object.freeze({ path: 'state/control.sqlite3' as const, bytes: bytes.byteLength, sha256: digest(bytes) })
    const unsigned = { bundleFormatVersion: 1 as const, projectId: 'quarkselfai-server' as const, createdAt: now.toISOString(), captureMode: 'sqlite-online-backup' as const, serverVersion: installation.serverVersion, sourceRevision: installation.sourceRevision, distributionDigest: installation.distributionDigest, sourceInstallationId: installation.installationId, owner: Object.freeze({ tenantId: owner.tenantId, userId: owner.userId, createdAt: owner.createdAt }), entries: Object.freeze([entry] as const), restorePolicy: Object.freeze({ requiresFreshInactiveInstallation: true as const, configurationRestored: false as const, serviceRegistered: false as const, sshGatewayApplied: false as const, autoStart: false as const, externalEffectsEnabled: false as const }) }
    const document = Object.freeze({ ...unsigned, bundleId: hash(JSON.stringify(unsigned)) })
    await writePrivate(join(bundleRoot, 'bundle.json'), Buffer.from(`${JSON.stringify(document)}\n`)); await run(binaries.tar, ['-czf', archivePath, '-C', temporary, 'bundle']); await run(binaries.age, ['-r', input.recipient, '-o', encryptedPath, archivePath]); await validateProducedFile(encryptedPath, 'server state output'); await chmod(encryptedPath, 0o600); await assertAgeFile(encryptedPath)
    await copyFile(encryptedPath, output, constants.COPYFILE_EXCL); outputCreated = true; await chmod(output, 0o600); return document
  } catch (error) { if (outputCreated) await rm(output, { force: true }); throw error } finally { await rm(temporary, { recursive: true, force: true }) }
}

/** Decrypts into a new staging directory and verifies paths, manifest identity, digest and SQLite integrity. */
export async function stageInactiveServerStateBundle(input: StageInactiveServerStateBundleInputV1): Promise<InactiveServerStateBundleV1> {
  const encrypted = await canonicalPrivateFile(input.inputPath, 2 ** 40, 'server state bundle'); const identity = await canonicalPrivateFile(input.identityFile, 1024 * 1024, 'server state identity'); const output = await exactNewDirectory(input.outputDirectory)
  await canonicalDirectory(dirname(output), 'server state staging parent'); await mkdir(output, { mode: 0o700 }); const binaries = { age: input.binaries?.age ?? 'age', tar: input.binaries?.tar ?? 'tar' }; const temporary = await mkdtemp(join(dirname(output), '.quark-server-stage-')); await chmod(temporary, 0o700)
  try {
    const archive = join(temporary, 'bundle.tar.gz'); await run(binaries.age, ['-d', '-i', identity, '-o', archive, encrypted]); await validateArchive(archive, binaries.tar)
    await run(binaries.tar, ['-xzf', archive, '-C', temporary]); const bundleRoot = join(temporary, 'bundle'); const document = await verifyStagedInactiveServerStateBundle(bundleRoot)
    await copyFile(join(bundleRoot, 'bundle.json'), join(output, 'bundle.json'), constants.COPYFILE_EXCL); await chmod(join(output, 'bundle.json'), 0o600); await mkdir(join(output, 'state'), { mode: 0o700 }); await copyFile(join(bundleRoot, 'state/control.sqlite3'), join(output, 'state/control.sqlite3'), constants.COPYFILE_EXCL); await chmod(join(output, 'state/control.sqlite3'), 0o600); await verifyStagedInactiveServerStateBundle(output); return document
  } catch (error) { await rm(output, { recursive: true, force: true }); throw error } finally { await rm(temporary, { recursive: true, force: true }) }
}

/** Materializes verified state only into a newly configured, inactive, empty installation. */
export async function prepareInactiveServerStateRestore(input: PrepareInactiveServerStateRestoreInputV1): Promise<InactiveServerStateRestoreReceiptV1> {
  const staging = await canonicalDirectory(input.stagingDirectory, 'server state staging'); const root = await canonicalDirectory(input.installRoot, 'server state restore root')
  const document = await verifyStagedInactiveServerStateBundle(staging); const installation = await recoverInactiveServerInstallation(root); await recoverInactiveServerConfiguration(root)
  if (installation.serverVersion !== document.serverVersion || installation.sourceRevision !== document.sourceRevision || installation.distributionDigest !== document.distributionDigest) throw new Error('server state restore distribution does not match the bundle')
  const runtime = join(root, 'runtime'); const state = join(root, 'state'); if ((await readdir(runtime)).length || (await readdir(state)).length) throw new Error('server state restore requires empty runtime and state')
  const target = join(state, 'control.sqlite3')
  let copied = false; let receiptCreated = false
  try {
    await copyFile(join(staging, 'state/control.sqlite3'), target, constants.COPYFILE_EXCL); copied = true; await chmod(target, 0o600); const targetBytes = await readFile(target); if (digest(targetBytes) !== document.entries[0].sha256 || targetBytes.byteLength !== document.entries[0].bytes) throw new Error('server state restore copy drifted')
    const owner = await repairInstalledFirstOwnerReceipt({ installRoot: root, tenantId: document.owner.tenantId, userId: document.owner.userId }); receiptCreated = true; if (owner.createdAt !== document.owner.createdAt) throw new Error('server state restore owner lineage drifted')
    return Object.freeze({ schemaVersion: 1, bundleId: document.bundleId, installationId: installation.installationId, state: 'owner-restored-inactive', serviceRegistered: false, sshGatewayApplied: false, autoStart: false, externalEffectsEnabled: false })
  } catch (error) { if (receiptCreated) await rm(join(state, 'owner-bootstrap-receipt.json'), { force: true }); if (copied) await rm(target, { force: true }); throw error }
}

export async function verifyStagedInactiveServerStateBundle(rootValue: string): Promise<InactiveServerStateBundleV1> {
  const root = await canonicalDirectory(rootValue, 'server state staging')
  if ((await readdir(root)).sort().join(',') !== 'bundle.json,state' || (await readdir(join(root, 'state'))).sort().join(',') !== 'control.sqlite3') throw new Error('server state staging layout is invalid')
  let raw: unknown; try { raw = JSON.parse(await readFile(await canonicalPrivateFile(join(root, 'bundle.json'), 1024 * 1024, 'server state manifest'), 'utf8')) } catch { throw new Error('server state bundle manifest is invalid') }; const document = exactBundle(raw)
  const database = await canonicalPrivateFile(join(root, 'state/control.sqlite3'), 2 ** 40, 'server state database'); const bytes = await readFile(database); const entry = document.entries[0]
  if (entry.bytes !== bytes.byteLength || entry.sha256 !== digest(bytes)) throw new Error('server state bundle database digest drifted'); const owner = await inspectInstalledFirstOwnerDatabase(database); if (owner.tenantId !== document.owner.tenantId || owner.userId !== document.owner.userId || owner.createdAt !== document.owner.createdAt) throw new Error('server state bundle owner lineage drifted'); return document
}

async function validateArchive(path: string, tar: string): Promise<void> { const list = (await run(tar, ['-tzf', path])).stdout.split(/\r?\n/).filter(Boolean); const allowed = new Set(['bundle/','bundle','bundle/bundle.json','bundle/state/','bundle/state','bundle/state/control.sqlite3']); if (!list.length || new Set(list).size !== list.length || list.some(item => !allowed.has(item)) || list.filter(item => item === 'bundle/bundle.json').length !== 1 || list.filter(item => item === 'bundle/state/control.sqlite3').length !== 1) throw new Error('server state archive layout is invalid'); const verbose = (await run(tar, ['-tvzf', path])).stdout.split(/\r?\n/).filter(Boolean); if (verbose.length !== list.length || verbose.some(line => line[0] !== '-' && line[0] !== 'd')) throw new Error('server state archive contains an unsupported entry') }
function exactBundle(value: unknown): InactiveServerStateBundleV1 { if (!record(value)) throw new Error('server state bundle manifest is invalid'); const keys = ['bundleFormatVersion','projectId','bundleId','createdAt','captureMode','serverVersion','sourceRevision','distributionDigest','sourceInstallationId','owner','entries','restorePolicy']; if (Object.keys(value).sort().join(',') !== keys.sort().join(',') || value.bundleFormatVersion !== 1 || value.projectId !== 'quarkselfai-server' || typeof value.bundleId !== 'string' || !digestPattern.test(value.bundleId) || typeof value.createdAt !== 'string' || Number.isNaN(Date.parse(value.createdAt)) || value.captureMode !== 'sqlite-online-backup' || typeof value.serverVersion !== 'string' || !/^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?$/.test(value.serverVersion) || typeof value.sourceRevision !== 'string' || !/^[a-f0-9]{40}$/.test(value.sourceRevision) || typeof value.distributionDigest !== 'string' || !digestPattern.test(value.distributionDigest) || typeof value.sourceInstallationId !== 'string' || !/^server-installation\.[a-f0-9]{32}$/.test(value.sourceInstallationId) || !record(value.owner) || Object.keys(value.owner).sort().join(',') !== 'createdAt,tenantId,userId' || typeof value.owner.tenantId !== 'string' || typeof value.owner.userId !== 'string' || typeof value.owner.createdAt !== 'string' || Number.isNaN(Date.parse(value.owner.createdAt)) || !Array.isArray(value.entries) || value.entries.length !== 1 || !record(value.entries[0]) || Object.keys(value.entries[0]).sort().join(',') !== 'bytes,path,sha256' || value.entries[0].path !== 'state/control.sqlite3' || !Number.isSafeInteger(value.entries[0].bytes) || (value.entries[0].bytes as number) <= 0 || typeof value.entries[0].sha256 !== 'string' || !digestPattern.test(value.entries[0].sha256) || !record(value.restorePolicy) || Object.keys(value.restorePolicy).sort().join(',') !== ['requiresFreshInactiveInstallation','configurationRestored','serviceRegistered','sshGatewayApplied','autoStart','externalEffectsEnabled'].sort().join(',') || value.restorePolicy.requiresFreshInactiveInstallation !== true || value.restorePolicy.configurationRestored !== false || value.restorePolicy.serviceRegistered !== false || value.restorePolicy.sshGatewayApplied !== false || value.restorePolicy.autoStart !== false || value.restorePolicy.externalEffectsEnabled !== false) throw new Error('server state bundle manifest is invalid'); const { bundleId, ...unsigned } = value; if (hash(JSON.stringify(unsigned)) !== bundleId) throw new Error('server state bundle identity drifted'); return Object.freeze(value as unknown as InactiveServerStateBundleV1) }
function record(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === 'object' && !Array.isArray(value) }
function validateRecipient(value: string): void { if (typeof value !== 'string' || (!value.startsWith('age1') && !value.startsWith('age-plugin-')) || /[\r\n\0]/.test(value)) throw new Error('server state backup recipient is invalid') }
async function exactNewPath(value: string, suffix: string): Promise<string> { if (!isAbsolute(value) || resolve(value) !== value || value === '/' || !value.endsWith(suffix) || /[\r\n\0]/.test(value)) throw new Error('server state output path is invalid'); await absent(value, 'server state output already exists'); return value }
async function exactNewDirectory(value: string): Promise<string> { if (!isAbsolute(value) || resolve(value) !== value || value === '/' || /[\r\n\0]/.test(value)) throw new Error('server state staging path is invalid'); await absent(value, 'server state staging already exists'); return value }
async function canonicalDirectory(value: string, label: string): Promise<string> { if (!isAbsolute(value) || resolve(value) !== value || value === '/' || await realpath(value) !== value) throw new Error(`${label} is invalid`); const state = await lstat(value); const uid = process.getuid?.(); if (!state.isDirectory() || state.isSymbolicLink() || (state.mode & 0o077) !== 0 || (uid !== undefined && state.uid !== uid)) throw new Error(`${label} is unsafe`); return value }
async function canonicalPrivateFile(value: string, max: number, label: string): Promise<string> { if (!isAbsolute(value) || resolve(value) !== value || await realpath(value) !== value) throw new Error(`${label} is invalid`); const state = await lstat(value); const uid = process.getuid?.(); if (!state.isFile() || state.isSymbolicLink() || state.nlink !== 1 || (state.mode & 0o077) !== 0 || state.size <= 0 || state.size > max || (uid !== undefined && state.uid !== uid)) throw new Error(`${label} is unsafe`); return value }
async function validateProducedFile(value: string, label: string): Promise<void> { const state = await lstat(value); const uid = process.getuid?.(); if (!state.isFile() || state.isSymbolicLink() || state.nlink !== 1 || state.size <= 0 || (uid !== undefined && state.uid !== uid) || await realpath(value) !== value) throw new Error(`${label} is unsafe`) }
async function assertAgeFile(path: string): Promise<void> { const handle = await open(path, 'r'); try { const bytes = Buffer.alloc(ageHeader.length); const result = await handle.read(bytes, 0, bytes.length, 0); if (result.bytesRead !== bytes.length || !bytes.equals(Buffer.from(ageHeader))) throw new Error('age did not produce a valid encrypted server state bundle') } finally { await handle.close() } }
async function absent(path: string, message: string): Promise<void> { try { await lstat(path); throw new Error(message) } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error } }
async function writePrivate(path: string, bytes: Uint8Array): Promise<void> { const handle = await open(path, 'wx', 0o600); try { await handle.writeFile(bytes); await handle.sync() } finally { await handle.close() } }
async function run(binary: string, args: string[]): Promise<{ stdout: string }> { return await runServerRecoveryProcess(binary, args) }
function digest(value: Uint8Array): string { return hash(value) }
function hash(value: string | Uint8Array): string { return `sha256:${createHash('sha256').update(value).digest('hex')}` }
