import { lstat, readFile, readdir, realpath } from 'node:fs/promises'
import { isAbsolute, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { provisionInactiveServerConfiguration, recoverInactiveServerConfiguration, removeUnusedServerConfiguration, type InactiveServerConfigurationInputV1 } from './server-configuration.js'
import { installInactiveServer, recoverInactiveServerInstallation, uninstallUnusedInactiveServer } from './server-installation.js'
import { bootstrapInstalledFirstOwner, recoverInstalledFirstOwner, repairInstalledFirstOwnerReceipt, type InstalledFirstOwnerInputV1, type InstalledFirstOwnerReceiptRepairV1 } from './server-owner-bootstrap.js'
import { createInactiveServerStateBundle, prepareInactiveServerStateRestore, stageInactiveServerStateBundle } from './server-state-recovery.js'

type ServerAdminCommandV1 = { readonly mode: 'install'; readonly distributionRoot: string; readonly installRoot: string } | { readonly mode: 'configure' | 'bootstrap-owner' | 'repair-owner-receipt'; readonly installRoot: string; readonly configPath: string } | { readonly mode: 'status' | 'remove-unused-configuration' | 'uninstall-unused'; readonly installRoot: string } | { readonly mode: 'backup-state'; readonly installRoot: string; readonly outputPath: string; readonly recipient: string } | { readonly mode: 'stage-state'; readonly inputPath: string; readonly outputDirectory: string; readonly identityFile: string } | { readonly mode: 'prepare-state-restore'; readonly stagingDirectory: string; readonly installRoot: string }
export interface ServerAdminReceiptV1 { readonly schemaVersion: 1; readonly operation: ServerAdminCommandV1['mode']; readonly installationId: string; readonly state: string; readonly bundleId?: string; readonly sourceRevision?: string; readonly distributionDigest?: string; readonly autoStart: false; readonly serviceRegistered: false; readonly sshGatewayApplied: false; readonly externalEffectsEnabled: false }

export function compileServerAdminCommand(argv: readonly string[]): ServerAdminCommandV1 {
  if (argv[0] === 'install' && argv.length === 3) return Object.freeze({ mode: 'install', distributionRoot: exactPath(argv[1]!), installRoot: exactPath(argv[2]!) })
  if ((argv[0] === 'configure' || argv[0] === 'bootstrap-owner' || argv[0] === 'repair-owner-receipt') && argv.length === 3) return Object.freeze({ mode: argv[0], installRoot: exactPath(argv[1]!), configPath: exactPath(argv[2]!) })
  if ((argv[0] === 'status' || argv[0] === 'remove-unused-configuration' || argv[0] === 'uninstall-unused') && argv.length === 2) return Object.freeze({ mode: argv[0], installRoot: exactPath(argv[1]!) })
  if (argv[0] === 'backup-state' && argv.length === 4) return Object.freeze({ mode: 'backup-state', installRoot: exactPath(argv[1]!), outputPath: exactPath(argv[2]!), recipient: exactRecipient(argv[3]!) })
  if (argv[0] === 'stage-state' && argv.length === 4) return Object.freeze({ mode: 'stage-state', inputPath: exactPath(argv[1]!), outputDirectory: exactPath(argv[2]!), identityFile: exactPath(argv[3]!) })
  if (argv[0] === 'prepare-state-restore' && argv.length === 3) return Object.freeze({ mode: 'prepare-state-restore', stagingDirectory: exactPath(argv[1]!), installRoot: exactPath(argv[2]!) })
  throw new Error('server admin command is invalid')
}

/** Executes one explicit local lifecycle operation. It never starts or registers the server. */
export async function runServerAdminEntry(argv: readonly string[], environment: NodeJS.ProcessEnv, credentialInput: AsyncIterable<Buffer | string>): Promise<ServerAdminReceiptV1> {
  if (environment.QUARK_SERVER_ADMIN_ENABLE !== '1') throw new Error('server admin entry is disabled'); const command = compileServerAdminCommand(argv)
  if (command.mode === 'install') return bounded(command.mode, await installInactiveServer(command.installRoot, command.distributionRoot))
  if (command.mode === 'configure') { const config = exactConfigureConfig(await readPrivateJson(command.configPath), command.installRoot); return bounded(command.mode, await provisionInactiveServerConfiguration(config)) }
  if (command.mode === 'bootstrap-owner') { const config = exactOwnerConfig(await readPrivateJson(command.configPath), command.installRoot); const credential = await readCredential(credentialInput); return bounded(command.mode, await bootstrapInstalledFirstOwner(config, credential)) }
  if (command.mode === 'repair-owner-receipt') { const config = exactOwnerRepairConfig(await readPrivateJson(command.configPath), command.installRoot); return bounded(command.mode, await repairInstalledFirstOwnerReceipt(config)) }
  if (command.mode === 'backup-state') { const result = await createInactiveServerStateBundle(command); return bounded(command.mode, { installationId: result.sourceInstallationId, state: 'encrypted-state-created', bundleId: result.bundleId, sourceRevision: result.sourceRevision, distributionDigest: result.distributionDigest }) }
  if (command.mode === 'stage-state') { const result = await stageInactiveServerStateBundle(command); return bounded(command.mode, { installationId: result.sourceInstallationId, state: 'decrypted-state-staged', bundleId: result.bundleId, sourceRevision: result.sourceRevision, distributionDigest: result.distributionDigest }) }
  if (command.mode === 'prepare-state-restore') return bounded(command.mode, await prepareInactiveServerStateRestore(command))
  if (command.mode === 'remove-unused-configuration') return bounded(command.mode, await removeUnusedServerConfiguration(command.installRoot))
  if (command.mode === 'uninstall-unused') return bounded(command.mode, await uninstallUnusedInactiveServer(command.installRoot))
  return await status(command.installRoot)
}

async function status(root: string): Promise<ServerAdminReceiptV1> { const state = await readdir(resolve(root, 'state')); const config = await readdir(resolve(root, 'config')); if (state.length) return bounded('status', await recoverInstalledFirstOwner(root)); if (config.length) return bounded('status', await recoverInactiveServerConfiguration(root)); return bounded('status', await recoverInactiveServerInstallation(root)) }
async function readPrivateJson(path: string): Promise<unknown> { const state = await lstat(path); const uid = process.getuid?.(); if (!state.isFile() || state.isSymbolicLink() || state.nlink !== 1 || (state.mode & 0o077) !== 0 || state.size <= 0 || state.size > 64 * 1024 || await realpath(path) !== path || (uid !== undefined && state.uid !== uid)) throw new Error('server admin config is unsafe'); try { return JSON.parse(await readFile(path, 'utf8')) } catch { throw new Error('server admin config is invalid') } }
function exactConfigureConfig(value: unknown, installRoot: string): InactiveServerConfigurationInputV1 { const item = exactRecord(value, ['tlsKeySourcePath','tlsCertSourcePath','host','port','requestTimeoutMs','maxConnections','sshRequestTimeoutMs','planVerification']); return { ...item, installRoot } as unknown as InactiveServerConfigurationInputV1 }
function exactOwnerConfig(value: unknown, installRoot: string): InstalledFirstOwnerInputV1 { const item = exactRecord(value, ['tenantId','tenantName','userId','displayName']); return { ...item, installRoot } as unknown as InstalledFirstOwnerInputV1 }
function exactOwnerRepairConfig(value: unknown, installRoot: string): InstalledFirstOwnerReceiptRepairV1 { const item = exactRecord(value, ['tenantId','userId']); return { ...item, installRoot } as unknown as InstalledFirstOwnerReceiptRepairV1 }
function exactRecord(value: unknown, keys: readonly string[]): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value) || Object.keys(value).sort().join(',') !== [...keys].sort().join(',')) throw new Error('server admin config is invalid'); return value as Record<string, unknown> }
async function readCredential(input: AsyncIterable<Buffer | string>): Promise<string> { const chunks: Buffer[] = []; let size = 0; for await (const chunk of input) { const bytes = Buffer.from(chunk); size += bytes.byteLength; if (size > 258) throw new Error('server admin credential is invalid'); chunks.push(bytes) }; const bytes = Buffer.concat(chunks); let value = bytes.toString('utf8'); bytes.fill(0); value = value.replace(/\r?\n$/, ''); if (!value || /[\r\n]/.test(value)) throw new Error('server admin credential is invalid'); return value }
function exactPath(value: string): string { if (!isAbsolute(value) || resolve(value) !== value || value === '/' || /[\r\n\0]/.test(value)) throw new Error('server admin path must be exact and absolute'); return value }
function exactRecipient(value: string): string { if ((!value.startsWith('age1') && !value.startsWith('age-plugin-')) || /[\r\n\0]/.test(value)) throw new Error('server admin recipient is invalid'); return value }
function bounded(operation: ServerAdminCommandV1['mode'], receipt: { readonly installationId: string; readonly state: string; readonly bundleId?: string; readonly sourceRevision?: string; readonly distributionDigest?: string }): ServerAdminReceiptV1 { return Object.freeze({ schemaVersion: 1, operation, installationId: receipt.installationId, state: receipt.state, ...(typeof receipt.bundleId === 'string' ? { bundleId: receipt.bundleId } : {}), ...(typeof receipt.sourceRevision === 'string' ? { sourceRevision: receipt.sourceRevision } : {}), ...(typeof receipt.distributionDigest === 'string' ? { distributionDigest: receipt.distributionDigest } : {}), autoStart: false, serviceRegistered: false, sshGatewayApplied: false, externalEffectsEnabled: false }) }

async function main(): Promise<void> { const receipt = await runServerAdminEntry(process.argv.slice(2), process.env, process.stdin); process.stdout.write(`${JSON.stringify(receipt)}\n`) }
if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url && fileURLToPath(import.meta.url) === resolve(process.argv[1])) void main().catch(() => { process.stderr.write('server-admin-failed\n'); process.exitCode = 1 })
