import { createHash } from 'node:crypto'
import { lstat, open, readFile, readdir, realpath, unlink } from 'node:fs/promises'
import { isAbsolute, join, resolve } from 'node:path'
import { recoverInstalledFirstOwner } from './server-owner-bootstrap.js'

export interface ServerServiceRenderOptionsV1 { readonly installRoot: string; readonly nodeExecutable: string; readonly stdoutPath: string; readonly stderrPath: string }
export interface PreparedServerServiceV1 { readonly schemaVersion: 1; readonly platform: 'launchd-user' | 'systemd-user'; readonly definition: string; readonly definitionDigest: string; readonly state: 'prepared-inactive'; readonly registered: false; readonly started: false; readonly singleProvider: true; readonly externalEffectsEnabled: false; readonly rollback: { readonly stopBeforeRemove: true; readonly removeDefinitionOnly: true; readonly preserveInstallationState: true } }
export interface InstalledServerServicePreparationInputV1 extends ServerServiceRenderOptionsV1 { readonly platform: PreparedServerServiceV1['platform'] }
export interface InstalledServerServicePreparationReceiptV1 { readonly schemaVersion: 1; readonly installationId: string; readonly configurationDigest: string; readonly platform: PreparedServerServiceV1['platform']; readonly definitionFile: 'com.quarkfan.quark-server.plist' | 'quark-server.service'; readonly definitionDigest: string; readonly nodeExecutable: string; readonly stdoutPath: string; readonly stderrPath: string; readonly preparedAt: string; readonly state: 'service-prepared-inactive'; readonly registered: false; readonly started: false; readonly autoStart: false; readonly singleProvider: true; readonly externalEffectsEnabled: false }

/** Renders one user LaunchAgent only. It does not write, register or start it. */
export function prepareInactiveServerLaunchd(template: string, options: ServerServiceRenderOptionsV1): PreparedServerServiceV1 { const values = checked(options); return prepared('launchd-user', replace(template, { __NODE_EXECUTABLE__: xml(values.nodeExecutable), __SERVER_ENTRY__: xml(join(values.installRoot, 'program/dist/control-plane/cloud-server-entry.js')), __SERVER_CONFIG__: xml(join(values.installRoot, 'config/server.json')), __PROGRAM_ROOT__: xml(join(values.installRoot, 'program')), __STDOUT_PATH__: xml(values.stdoutPath), __STDERR_PATH__: xml(values.stderrPath) })) }

/** Renders one systemd user unit only. It does not write, enable or start it. */
export function prepareInactiveServerSystemd(template: string, options: ServerServiceRenderOptionsV1): PreparedServerServiceV1 { const values = checked(options); for (const value of Object.values(values)) if (/\s|["\\]/.test(value)) throw new Error('systemd server service paths cannot contain whitespace, quote or backslash'); return prepared('systemd-user', replace(template, { __NODE_EXECUTABLE__: values.nodeExecutable, __SERVER_ENTRY__: join(values.installRoot, 'program/dist/control-plane/cloud-server-entry.js'), __SERVER_CONFIG__: join(values.installRoot, 'config/server.json'), __PROGRAM_ROOT__: join(values.installRoot, 'program'), __STDOUT_PATH__: values.stdoutPath, __STDERR_PATH__: values.stderrPath })) }

/** Persists a sealed, disabled definition inside the installation. It does not touch a service-manager directory. */
export async function prepareInstalledServerUserService(input: InstalledServerServicePreparationInputV1, now = new Date()): Promise<InstalledServerServicePreparationReceiptV1> {
  const values = exactPreparationInput(input); if (Number.isNaN(now.getTime())) throw new Error('server service preparation timestamp is invalid')
  const owner = await recoverInstalledFirstOwner(values.installRoot); const serviceRoot = join(values.installRoot, 'service'); await privateDirectory(serviceRoot)
  if ((await readdir(serviceRoot)).length) throw new Error('server service preparation already exists')
  const template = await readPrivate(templatePath(values.installRoot, values.platform), 64 * 1024); const options = { installRoot: values.installRoot, nodeExecutable: values.nodeExecutable, stdoutPath: values.stdoutPath, stderrPath: values.stderrPath }
  const preparedService = values.platform === 'launchd-user' ? prepareInactiveServerLaunchd(template.toString('utf8'), options) : prepareInactiveServerSystemd(template.toString('utf8'), options)
  const definitionFile = values.platform === 'launchd-user' ? 'com.quarkfan.quark-server.plist' as const : 'quark-server.service' as const; const definitionPath = join(serviceRoot, definitionFile); const receiptPath = join(serviceRoot, 'preparation-receipt.json')
  const receipt = Object.freeze({ schemaVersion: 1 as const, installationId: owner.installationId, configurationDigest: owner.configurationDigest, platform: values.platform, definitionFile, definitionDigest: preparedService.definitionDigest, nodeExecutable: values.nodeExecutable, stdoutPath: values.stdoutPath, stderrPath: values.stderrPath, preparedAt: now.toISOString(), state: 'service-prepared-inactive' as const, registered: false as const, started: false as const, autoStart: false as const, singleProvider: true as const, externalEffectsEnabled: false as const })
  try { await writePrivate(definitionPath, Buffer.from(preparedService.definition)); await writePrivate(receiptPath, Buffer.from(`${JSON.stringify(receipt)}\n`)); return receipt } catch (error) { for (const path of [receiptPath, definitionPath]) { try { await unlink(path) } catch {} }; throw error }
}

/** Re-renders from sealed inputs and verifies the staged definition without registering it. */
export async function recoverPreparedServerUserService(installRoot: string): Promise<InstalledServerServicePreparationReceiptV1> {
  const root = await exactExistingRoot(installRoot); const owner = await recoverInstalledFirstOwner(root); const serviceRoot = join(root, 'service'); await privateDirectory(serviceRoot)
  const receipt = exactPreparationReceipt(JSON.parse((await readPrivate(join(serviceRoot, 'preparation-receipt.json'), 64 * 1024)).toString('utf8')))
  if (receipt.installationId !== owner.installationId || receipt.configurationDigest !== owner.configurationDigest) throw new Error('server service preparation lineage drifted')
  if ((await readdir(serviceRoot)).sort().join(',') !== [receipt.definitionFile, 'preparation-receipt.json'].sort().join(',')) throw new Error('server service preparation layout is invalid')
  const template = await readPrivate(templatePath(root, receipt.platform), 64 * 1024); const definition = await readPrivate(join(serviceRoot, receipt.definitionFile), 64 * 1024)
  const options = { installRoot: root, nodeExecutable: receipt.nodeExecutable, stdoutPath: receipt.stdoutPath, stderrPath: receipt.stderrPath }; const rendered = receipt.platform === 'launchd-user' ? prepareInactiveServerLaunchd(template.toString('utf8'), options) : prepareInactiveServerSystemd(template.toString('utf8'), options)
  if (rendered.definitionDigest !== receipt.definitionDigest || definition.toString('utf8') !== rendered.definition) throw new Error('server service preparation digest drifted')
  return receipt
}

/** Removes only a verified definition that was never registered or started. */
export async function removeUnregisteredServerUserService(installRoot: string): Promise<InstalledServerServicePreparationReceiptV1> { const root = await exactExistingRoot(installRoot); if ((await readdir(join(root, 'runtime'))).length) throw new Error('server service preparation has runtime state'); const receipt = await recoverPreparedServerUserService(root); await unlink(join(root, 'service', receipt.definitionFile)); await unlink(join(root, 'service/preparation-receipt.json')); return receipt }

function checked(options: ServerServiceRenderOptionsV1): ServerServiceRenderOptionsV1 { if (!options || typeof options !== 'object' || Object.keys(options).sort().join(',') !== ['installRoot','nodeExecutable','stdoutPath','stderrPath'].sort().join(',')) throw new Error('server service options are invalid'); for (const value of Object.values(options)) exactServicePath(value); return options }
function exactPreparationInput(value: unknown): InstalledServerServicePreparationInputV1 { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('server service preparation input is invalid'); const item = value as Record<string, unknown>; if (Object.keys(item).sort().join(',') !== ['installRoot','platform','nodeExecutable','stdoutPath','stderrPath'].sort().join(',') || (item.platform !== 'launchd-user' && item.platform !== 'systemd-user')) throw new Error('server service preparation input is invalid'); checked({ installRoot: item.installRoot, nodeExecutable: item.nodeExecutable, stdoutPath: item.stdoutPath, stderrPath: item.stderrPath } as ServerServiceRenderOptionsV1); return item as unknown as InstalledServerServicePreparationInputV1 }
function exactPreparationReceipt(value: unknown): InstalledServerServicePreparationReceiptV1 { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('server service preparation receipt is invalid'); const item = value as Record<string, unknown>; const keys = ['schemaVersion','installationId','configurationDigest','platform','definitionFile','definitionDigest','nodeExecutable','stdoutPath','stderrPath','preparedAt','state','registered','started','autoStart','singleProvider','externalEffectsEnabled']; if (Object.keys(item).sort().join(',') !== keys.sort().join(',') || item.schemaVersion !== 1 || typeof item.installationId !== 'string' || !/^server-installation\.[a-f0-9]{32}$/.test(item.installationId) || typeof item.configurationDigest !== 'string' || !/^sha256:[a-f0-9]{64}$/.test(item.configurationDigest) || !((item.platform === 'launchd-user' && item.definitionFile === 'com.quarkfan.quark-server.plist') || (item.platform === 'systemd-user' && item.definitionFile === 'quark-server.service')) || typeof item.definitionDigest !== 'string' || !/^sha256:[a-f0-9]{64}$/.test(item.definitionDigest) || typeof item.preparedAt !== 'string' || Number.isNaN(Date.parse(item.preparedAt)) || item.state !== 'service-prepared-inactive' || item.registered !== false || item.started !== false || item.autoStart !== false || item.singleProvider !== true || item.externalEffectsEnabled !== false) throw new Error('server service preparation receipt is invalid'); for (const name of ['nodeExecutable','stdoutPath','stderrPath']) exactServicePath(item[name]); return Object.freeze(item as unknown as InstalledServerServicePreparationReceiptV1) }
function exactServicePath(value: unknown): string { if (typeof value !== 'string' || !isAbsolute(value) || resolve(value) !== value || value === '/' || /[\0\r\n]/.test(value)) throw new Error('server service paths must be exact and absolute'); return value }
function templatePath(root: string, platform: PreparedServerServiceV1['platform']): string { return join(root, platform === 'launchd-user' ? 'program/deploy/launchd/com.quarkfan.quark-server.plist.template' : 'program/deploy/systemd/quark-server.service.template') }
async function exactExistingRoot(value: string): Promise<string> { if (!isAbsolute(value) || resolve(value) !== value || value === '/' || await realpath(value) !== value) throw new Error('server service installation root is invalid'); return value }
async function privateDirectory(path: string): Promise<void> { const state = await lstat(path); const uid = process.getuid?.(); if (!state.isDirectory() || state.isSymbolicLink() || (state.mode & 0o077) !== 0 || await realpath(path) !== path || (uid !== undefined && state.uid !== uid)) throw new Error('server service directory is unsafe') }
async function readPrivate(path: string, max: number): Promise<Buffer> { const state = await lstat(path); const uid = process.getuid?.(); if (!state.isFile() || state.isSymbolicLink() || state.nlink !== 1 || (state.mode & 0o077) !== 0 || state.size <= 0 || state.size > max || await realpath(path) !== path || (uid !== undefined && state.uid !== uid)) throw new Error('server service file is unsafe'); return await readFile(path) }
async function writePrivate(path: string, bytes: Uint8Array): Promise<void> { const handle = await open(path, 'wx', 0o600); try { await handle.writeFile(bytes); await handle.sync() } finally { await handle.close() } }
function replace(template: string, values: Readonly<Record<string, string>>): string { let output = template; for (const [key, value] of Object.entries(values)) output = output.replaceAll(key, value); if (/__[A-Z_]+__/.test(output)) throw new Error('server service template contains unresolved placeholders'); return output }
function prepared(platform: PreparedServerServiceV1['platform'], definition: string): PreparedServerServiceV1 { if (!definition.includes('QUARK_CLOUD_SERVER_ENABLE') || /API_KEY|TOKEN|PASSWORD|PRIVATE_KEY|CLIENT_SECRET/i.test(definition)) throw new Error('server service definition is unsafe'); return Object.freeze({ schemaVersion: 1, platform, definition, definitionDigest: `sha256:${createHash('sha256').update(definition).digest('hex')}`, state: 'prepared-inactive', registered: false, started: false, singleProvider: true, externalEffectsEnabled: false, rollback: Object.freeze({ stopBeforeRemove: true, removeDefinitionOnly: true, preserveInstallationState: true }) }) }
function xml(value: string): string { return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&apos;') }
